### ISSUE TITLE
Change difficulty adjustment to target mean block time including uncles

### ISSUE THREAD

**Issue by vbuterin** [ethereum/EIPs#100]
### Specification

Currently, the formula to compute the difficulty of a block includes the following logic:

``` python
adj_factor = max(1 - ((timestamp - parent.timestamp) // 10), -99)
child_diff = int(max(parent.difficulty + (parent.difficulty // BLOCK_DIFF_FACTOR) * adj_factor, min(parent.difficulty, MIN_DIFF)))
...
```

If `block.number >= METROPOLIS_FORK_BLKNUM`, we change the first line to the following:

``` python
adj_factor = max(1 + len(parent.uncles) - ((timestamp - parent.timestamp) // 9), -99)
```
### Specification (1b)

``` python
adj_factor = max((2 if len(parent.uncles) else 1) - ((timestamp - parent.timestamp) // 9), -99)
```
### Rationale

This new formula ensures that the difficulty adjustment algorithm targets a constant average rate of blocks produced including uncles, and so ensures a highly predictable issuance rate that cannot be manipulated upward by manipulating the uncle rate. The formula can be fairly easily seen to be (to within a tolerance of ~3/4194304) mathematically equivalent to assuming that a block with `k` uncles is equivalent to a sequence of `k+1` blocks that all appear with the exact same timestamp, and this is likely the simplest possible way to accomplish the desired effect.

Changing the denominator from 10 to 9 ensures that the block time remains roughly the same (in fact, it should decrease by ~3% given the current uncle rate of 7%).

(1b) accomplishes almost the same effect but has the benefit that it depends only on the block header (as you can check the uncle hash against the blank hash) and not the entire block.

### Update 2017.06.29

Version (1b) was chosen.

**Comment by wanderer** [comment]
lgtm

**Comment by SergioDemianLerner** [comment]
lgtm.
If the uncle rate decreases, the avg block rate will slightly increase, forcing an increase in the uncle rate. 
If the uncle rate increases, the avg block rate will slightly decrease, forcing an decrease in the uncle rate.
Nice negative feedback. 
If block reward depended on the current block rate, so that reward/sec were always constant, block rate could be freely chosen by the network and the difficulty adjustment formula could allow decreasing block rate down to 5 secs if network conditions tolerate it. All dynamic.

**Comment by gumb0** [comment]
Uncle number is not the part of the header, so now to validate the header we need not only the parent header, but parent body, too. Wouldn't this cause troubles for the light clients?

**Comment by pirapira** [comment]
The activation should be `BYZANTIUM_FORK_BLKNUM` now.

**Comment by marcogiglio** [comment]
The proposed change has a negative conseguence on the effective gas throughtput of the network per second. Since uncle rates increas 0.77% per each additional 1M unit of gas consumed, after applying this change, increasing the block gas limit would increase the number of uncles, which have no effect on the state, lowering the effective throughput per second. The effect becomes evident already at around 20M block gas limit, where the available throughtput is around 80% of what would be with today difficulty.

**Comment by Souptacular** [comment]
@vbuterin This needs to be a PR.

**Comment by jamesray1** [comment]
When you make a PR maybe just include the chosen option 1b.

**Comment by nicksavers** [comment]
PR has been merged and EIP is active in the main repository with status Final
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-100.md
@vbuterin The document still references this issue for discussion, but I imagine it can be closed.
