### ISSUE TITLE
ERC-1178: Multi-Class Fungible Token Standard

### ISSUE THREAD

**Issue by albertchon** [ethereum/EIPs#1179]

**Comment by coinfork** [comment]
This is essentially what we're doing in ERC-1155, I suggest contributing to that EIP instead.

**Comment by PhABC** [comment]
Commenting here instead of the pull request ; 

The way I see it, #1178 is specifically for fungible tokens (which is [what we need as well](https://github.com/horizon-games/multi-fungible-tokens)), while #1155 wants to support both NFTs and FTs within a single contract. In this case, I see 1178 being a subset of 1155, where all tokens are fungible. Or, 1155 as being 1178 with "Class ID Specific Logic" functionality (some IDs are fungible tokens, some aren't). I talk about this a bit more in #1155.

**Comment by achon22** [comment]
It does indeed seem the case that the multi-class functionality can be modeled using the 1155 standard. However, as I mentioned in the pull request, conforming to this standard introduces additional complexity which not all developers may want to deal with (I certainly feel this way). 

I've found that a different team interested in implementing security tokens also took a look at #1155 and found it to be unnecessarily complex and preferred a standalone multi-class standard. 

Why shouldn't we allow for both standards to exist? For including NFTs, #1155 has its benefits and for MCFTs (multi-class fungible tokens) #1178 has its own.

**Comment by PhABC** [comment]
Yes, I agree with what you just said ^. Check out my [last comment](https://github.com/ethereum/EIPs/issues/1155#issuecomment-408571004) in #1155 and see if that seems like a more appropriate route.

**Comment by HassanFahmy** [comment]
Proposing to add an event to log the conversion between classes/ filling bids for conversion.
