### ISSUE TITLE
Trophy smart contract standard or draft

### ISSUE THREAD

**Issue by Azephiar** [ethereum/EIPs#1194]
We're building a dapp that will award a trophy as a smart contract, I tried to look on google if there is a draft or standard for something like that but I wasn't lucky.
The trophy is basically a transferable token with a supply of 1, it seems a little bit overkill using the ERC721, ERC20 or ERC223 interfaces. 

Just to give you a better idea the contract should have these variables:
- winner: Address that won the trophy
- creator: Address that created the trophy
- congratulations text: A text describing the trophy, this is hardcoded in the contract
- message: A message decided by the winner when he will claim the trophy
- name: Name of the trophy
- owner: Owner of the trophy (is transferable)

A function to award the trophy callable just once by the creator and a function to transfer the trophy.

Does someone have any idea where I should look?

**Comment by thekrol01** [comment]
You can also create a mapping with a struct like mapping(address (this is the creator)=> mapping( address(this is the winner)=>trophy) _trophy
The trophy struct contains all the contract details. So you don't need a new contract for every trophy. You can transfer to throphy to a new winner by whoeever is authorized.  For example a tournementowner. For example you can add a trophyowner address field  and congratulations field in the struct. You can als add some basic ERC20 functions like transfer, to ' transfer'  an trophy to a new winner.

**Comment by Ezechiele** [comment]
The Dapp I'm building will award just one trophy, so this was thought in that way.

Do you have any case scenarios where is needed to award a big amount of trophies ( > 10 )? Because if you don't I don't see the need to have a single contract awarding a lot of trophies.

If 1 smart contract = 1 trophy and someone has the need to award multiple trophies nothing is preventing to create a "Trophy Factory" that creates multiple instances of a single trophy contract.

But for sure what you said needs to be kept in consideration, for now, I just wait for other opinions from the community hoping that someone else already drafted something similar!

**Comment by AC0DEM0NK3Y** [comment]
I'm not sure you should be using the EIP process for asking questions like this, perhaps stack exchange.

You could use 721 or 1155 for something like this just fine and after creating your "trophy" just set a uri that points to off-chain storage for all of that you want to set, even just use the uri as the storage, it's just a string you can put whatever you want in it. Or you could have a function specific to your use case to set the metadata pieces you want like winner explicitly under a struct as @thekrol01 says.

If you don't use something (like 721) that is likely to be more in use than your particular case and only offers specific features then I think it will be hard to find wallets etc. to display your items for your users personally.

**Comment by Ezechiele** [comment]
As you suggested I'm probably going to use the ERC721 standard. Now I have two options: 

- Storing data on a struct inside the contract

- Storing data off-chain on something like ipfs
 
In both cases whoever wants to create an interface to interact with trophies has to implement a system to interact with the new variables. 

My only concern here is if I have to think for the community or just for my particular case, if I had to think just for my case I would save the data inside a struct in the contract because I have just one trophy and thus no 'minting costs'.

For the community, it's probably better to use an external JSON file because it's likely that someone will need to mint multiple trophies, and this would keep the cost lower.

Probably implementing both ways is my best option.

What would you do if you were in my position? 

Another question, why I shouldn't have asked this here but on StackExchange?
