### ISSUE TITLE
Replace (ORIGIN) and (SENDER) with (CALLSTACKSIZE) and (CALLSTACK <N>)

### ISSUE THREAD

**Issue by ebuchman** [ethereum/EIPs#128]
Currently, contracts have no access to the call stack. Access to callstack size can help with the callstack bound, assuming we don't do https://github.com/ethereum/EIPs/issues/114 instead. It can also help avoid re-entrency style bugs by enforcing how many calls deep a contract is willing to be called from (maybe it wants to only accept calls from user accounts), or other access control policies like who the contract 2 up the call stack must be, etc.

In addition to making contracts potentially more secure, these opcodes can replace ORIGIN and SENDER, as ORIGIN becomes (CALLSTACK 0) and SENDER is (CALLSTACK (- CALLSTACKSIZE 1)).

**Comment by Smithgift** [comment]
I'm in favor of this, though I haven't though through technical details.

**Comment by axic** [comment]
Why replace those two opcodes and not just introduce these new ones?

I would think opcodes can be deprecated/removed, but their slot shouldn't be reused, especially if we have so many empty slots.

**Comment by nmushegian** [comment]
I don't think exposing the stack depth is a good abstraction. `tx.origin` exists because it is an extra special address, it's the one that signed the transaction (it's attached to `tx`, not `msg`).

I strongly believe you don't need anything more than the sender abstraction, and anymore more introduces very unintuitive behavior which could be exploitable
