### ISSUE TITLE
Require ERC20 token creations emit Transfer event

### ISSUE THREAD

**Issue by medvedev1088** [ethereum/EIPs#1298]
Here is how the standard looks like in regards to `Transfer` event https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#transfer-1:

> Transfer
> MUST trigger when tokens are transferred, including zero value transfers.
> 
> **A token contract which creates new tokens SHOULD trigger a Transfer event with the _from address set to 0x0 when tokens are created.**

Is there any reason for **SHOULD** keyword for the case when tokens are created? **MUST** here makes it much easier to track the balances of tokens. 

Imagine a scenario:

1. `mint()` function was called on the token contract and 100 tokens were created and deposited to the address `0x123`. There was no `Transfer` event emitted for token creations.

The problem now is that it's impossible to figure out that the address `0x123` has the balance of 100 tokens other than inspecting **all** the transactions since that particular token contract was created (not only the transactions to that contract but the transactions to all contracts). The reason for this is:

- There is no way to list all the token holders addresses from the contract because the `mapping` type is not enumerable.
- The reason all transactions have to be inspected and not just the transactions targeted to the token contract is that the call to `mint()` could have been made from another contract, thus making it an internal transaction.

Using **MUST** instead of **SHOULD** solves the issue of knowing token balances for the scenario above.

**Comment by MicahZoltu** [comment]
ERC20 was a retroactive standard.  It wasn't finalized until after many tokens were launched as "ERC20".  This resulted in things being SHOULD instead of MUST because not all ERC20 tokens followed the rule, so setting it as MUST would have resultised in some tokens that were already known commonly as ERC20 tokens suddenly not being ERC20.

Because of this, the standard has many things wrong with it which is why new, better, token standards are being developed like ERC-777.
