### ISSUE TITLE
ERC-1328 - WalletConnect Standard URI Format

### ISSUE THREAD

**Issue by pedrouid** [ethereum/EIPs#1328]
eip: 1328
    title: WalletConnect Standard URI Format
    authors: ligi <ligi@ligi.de>, Pedro Gomes <pedrouid@protonmail.com>
    type: Standards Track
    category: ERC
    status: WIP
    created: 2018-08-15
    discussions-to: https://ethereum-magicians.org/t/wallet-connect-eip/850
    requires: 831

## Simple Summary

A standard way of creating WalletConnect URIs for establishing connections between wallets and dapps

## Abstract

Sesion data in QR codes for initiating a connection between a wallet and dapp using the WalletConnect standard require a standardized URI format for effictively parsing the intenet. This ERC is expandable between versions of the standard and also mobile-to-mobile deep links.

### Syntax

Function call URIs follow the ERC-831 URI format, with the following parameters:

    request            = "ethereum" ":" [ "wc-" ]sessionID [ "@" version ] [ "?" parameters ]
    sessionID          = STRING
    version            = 1*DIGIT
    parameters         = parameter *( "&" parameter )
    parameter          = key "=" value
    key                = "name" / "bridge" / "symKey"
    value              = NUMBER / STRING

### Semantics

Required parameters are dependent on the WalletConnect standard version which currently is specified to only include mobile-to-desktop connection sessions which only require `name` which describes the dapp name, `bridge` which includes the bridge URL, `symKey` which includes the symmetric key in base64.

## Rationale

The need for this ERC stems from the discussion to move away from JSON format used in current beta version of the WalletConnect standard which makes for very inneficient parsing of the intent of the QR code, making it easier to create better QR code parsers APIs for Wallets to implement for other compatible EIPs using the ERC-831 URI format for Ethereum.

## References

1. ERC-831, http://eips.ethereum.org/EIPS/eip-831

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by ligi** [comment]
Great! Some minor nit-picks:

I think TYPE should be removed or defined. I would vote for removing it

Btw: It is better to directly start your EIP as a PR - so one can directly write comments like the above on the corresponding line. Also You do not have this waste and overhead of having issue+pr.

I would leave out:

> Optional parameters can include vanity parameters as color or image for providing additional UI elements for displaying the connection and transaction requests for the WalletConnect session

and properly add this when a new version is created. Otherwise this opens it up for getting really messy- people will just start using their custom solutions under the banner of "Optional parameters" and we will loose interoperability and open the door for bugs from this corner.

Also I think we should define the length of symKey

I would replace dapp with application ;-) - you know the context - just for context for others: https://twitter.com/mr_ligi/status/1029682384965316608

Perhaps also this link should be added for context and discussion https://ethereum-magicians.org/t/wallet-connect-eip/850

Other than that - great! Let's finalize and implement - I Think I can have [WallETH](https://waleth.org) compatible to this today ,-)

**Comment by pedrouid** [comment]
@ligi I've made a few changes and submitted a PR

**Comment by ligi** [comment]
@pedrouid I think this issue can be closed
