### ISSUE TITLE
ERC-1332: Global Messaging Hub

### ISSUE THREAD

**Issue by trigun0x2** [ethereum/EIPs#1332]
```
eip: 1332
title: Global Messaging Hubg
author: Jeffrey Tong <hi@itsjefftong.com>
discussions-to: this issue
status: WIP
type: Standards Track
category: ERC
created: 2018-08-17
```
# Simple Summary
This a proposal for an open standard for smart contract to user notifications.
# Abstract
Smart contracts will make an external call to the message hub (will now be referred as Shout) with the appropriate data. The initial version of Shout expects these messages to be ephemeral, low cost and does not promise privacy. Third parties can then call Shout functions to retrieve messages and deliver the message to users. Third party integrations can include wallets (Metamask, Toshi), email, SMS or any other service.

# Specification
Smart contracts should call the Global Messaging Hub with the following:
```
address to: who the message is for
byte hash/url: link of data schema. This could be IPFS, Swarm, AWS, etc. (Debatable). Please consider cost of storage, availability, and lifespan.
byte var_data: replacement of variables in the data schema with on-chain data. 
I.e. {name: "bob"}
```
Shout expects third parties to store a local cached version of messages after they are retrieved.

There will be other functions to retrieve messages with filters and delete messages. If there’s any other valuable functions I may have missed, please include them in the comments.
### Data Schema:
This is a very preliminary attempt at the schema, would love feedback. Current version is inspired by Apple’s notifications.
**From:** Friendly App Name
**Message:** Text message
**Destination URL:** URL to direct user (i.e. TCR listing, Augur market)
**Optional:** Additional data to provide better UX/UI similar to iOS. This is up to the wallet to create integrations (i.e. badge, sound).
```
{
   "from": "test-app",
   "message": "Hello ${name}, your Cryptokitty has been challenged in a battle!",
   "destination": "https://crypto.kitties/12313/mybattles",
   "optional": ""
}

```
## Message Delivery:
This is heavily optional and will depend on what the user prefers.
Some options:
Metamask/Chrome Extensions
Native wallets
Mobile wallets
SMS
Email

## User Consent:
This is up for discussion but I am in favor of user opt-in on the message delivery layer. For example, Metamask can ask an user to opt-in for notifications upon the user’s first transaction with Cryptokitties.

## Ethereum Ecosystem:
Older messages will be deleted to help refund gas to the message sender and also help keep the Ethereum blockchain healthy.
# Rationale
Currently, the best way for Dapps to notify users is through a centralized services that is specific to the Dapp. In truth, most Dapps do not have a method for notifying users of activities. This means users will have to constantly check the Dapps site or user off-chain services to monitor the Ethereum chain.

I have proposed one central place for all smart contract to pass messages to users. This will reduce redundancy for consumers and for third party services. The Shout contract is agnostic to content and messages as the users/wallet is responsible for censoring/whitelisting messages.
Implementations
In the works.
# Copyright
Copyright and related rights waived via CC0.

**Comment by trigun0x2** [comment]
Requesting feedback: @danfinlay

**Comment by danfinlay** [comment]
Hi @trigun0x2!

I like how you've kept "what gets delivered" very open ended, and so I guess a lot of the final spec will fall on different clients to define how they deliver messages. I basically agree with the idea you've laid out, a new permission Dapps can request, for the client to track its messages.

As for the message schema, I know platforms can vary a lot as far as what they allow, like some can include an image, and some can include multiple buttons. Maybe this could just mean keeping some optional keys on there, like `image`, where you will hit some of the same challenges [we're addressing in EIP 747, to keep image formats platform agnostic](https://ethereum-magicians.org/t/eip-747-eth-watchtoken/1048).

I notice you're also using some templating in the message field. I'm wondering where you'd get these variables from. Maybe this would be something like [Aragon's Radspec](https://github.com/aragon/radspec) or [Mist's Moon Language](https://www.ethnews.com/moon-updated-ethereum-browser-unveiled-at-devcon3), but in general I don't think templating on the blockchain has been quite solved yet, so I might leave that for a future extension of the proposal, since I'm not sure there's a great solution right now.

Other than that, looks good, I think this could add a lot of async interactivity to blockchain applications.

**Comment by lsaether** [comment]
This reminds me of an old PoC of an[ Emailer smart contract ](https://github.com/lsaether/Emailer.sol/blob/master/Emailer.sol)I put together a while ago. The idea was that it would enable someone to set up a server which would watch for events from the Emailer contract and send an email with the message in the log. The fields that I used for this were `sender`, `recipient` and `msg.` I see that you've included an `optional` filed on top of these which I generally agree with. 

However, I'm wondering what the purpose of defining a standard would be instead of allowing DApp developers to implement their own notification systems. Could you provide some examples?

**Comment by trigun0x2** [comment]
@lsaether the benefit of a standard if mostly for the third-party services that deliver the message to the user.
For example: Metamask can now have a central hub for all the messages such that it is much easier to fetch/delete messages.
The final goal here is that any ETH dev can tap into these last mile notification services by just adding a line into their smart contract code.

**Comment by trigun0x2** [comment]
@danfinlay Thanks a lot of the feedback!
With regards to message schema, I was hoping the `optional` field would take care of most app specific cases and I've only included what I believe is core to all messages.
After chatting with @expede, I may make some changes on the template storage side of things. Integration with Radspec would be great, I have to chat with Aragon a bit more. My current solution allows the third party "final mile" message delivery services (such as MetaMask) to do the final interpolation. On chain templating is doable but I haven't explored the issues yet.

**Comment by fulldecent** [comment]
Here is a much cheaper implementation of the ideas in this proposal.

Standardize a convention for capturing account-targeted messages. Do this as an event.

```solidity
emit ShoutToAccount(indexed account recipient, string message);
```

When the client logs in then they can scan the blockchain for all events from any contract that have this type of event. Then they. record the last scanned block number. Then next time they resume searching from that block.

**Comment by trigun0x2** [comment]
> Here is a much cheaper implementation of the ideas in this proposal.
> 
> Standardize a convention for capturing account-targeted messages. Do this as an event.
> 
> ```solidity
> emit ShoutToAccount(indexed account recipient, string message);
> ```
> 
> When the client logs in then they can scan the blockchain for all events from any contract that have this type of event. Then they. record the last scanned block number. Then next time they resume searching from that block.

This was the original implementation but due to the nature of MetaMask at the time, it was not ensured that all events will be accounted for. Therefore the implementation I mentioned above.
