### ISSUE TITLE
Remove the need of transaction fees by rate limiting transaction based on address balance

### ISSUE THREAD

**Issue by wighawag** [ethereum/EIPs#135]
Transaction fees are an issue for ethereum adoption. This is more so than in bitcoin case since ethereum use case is far wider. Paying a fee for a tx that does not involve a penny is not user friendly.  
Instead of looking at workaround (https://github.com/ethereum/EIPs/issues/61) I suggest here to remove the need of tx fee entirely from ethereum. 

Steem use such system and describes it in its white paper : https://steem.io/SteemWhitePaper.pdf

The idea is to dynamically calculate the available global bandwidth and distribute the bandwidth to each address based on their balance and past tx history.

More a address has balance, more it can send tx per amount of time. Every address that do not participate in tx gives away its allowed bandwidth to the global bandwidth so it can be distributed to the addresses that actually need it.

Steem's white paper go in details how this can be implemented and show bitcoin as an example where if such system would be in place, you would gave 5 tx  per week per btc.

This would need to be applied to ethereum's gas system (instead of only bandwidth) but I don't see any obvious blockers.
What do you think?

**Comment by Smithgift** [comment]
I think it's worth considering, for the simple benefit to every user. However, I think it's technically impossible *on a protocol level* due to the nature of Ethereum.

As I understand it, Steem has a dynamic fractional reserve system, where the amount of transactions each account has a "right" to is more than the total blocksize available. I'm not sure how Steem decides who gets in if they run out.

In Ethereum, a contract could pay a miner before or after sending a transaction. Ergo, users can pay transaction fees whether or not the protocol says so, and miners can accept transaction fees in the same way. Even if there were "free" transactions, miners could prefer transactions that pay, or ignore ones that don't.

A contract can also forward a transaction, based on payment. Ergo, users can pay other users for use of their "free" transactions. This is not a horrible thing in and of itself, but it would circumvent the system.

Finally, I'm not sure why miners are incentivized to include transactions. A miner could always pretend that it didn't see a transaction. Or, if miners are paid for transactions by the network itself, there's an incentive to spam the network with fake transaction. In any case, if the network pays, the question is *how.* Steem involves quite large subsidies, which Ethereum could not support without altering the ETH issuing rate.

This may be possible, and quite helpful, for a dapp, but I don't think it can be enforced network-wide,
