### ISSUE TITLE
Where is the auto-merger maintained and run?

### ISSUE THREAD

**Issue by bmann** [ethereum/EIPs#1831]
Where is the auto-merger code maintained and who / where is it run?

Can we help in improving the code and improve its operation so that “pinging people in Gitter” isn’t how to file that’s it down? Installing monitoring that notifies people that can fix it might be a first step. 

Cc @axic

**Comment by bmann** [comment]
Answer: https://github.com/eip-automerger/automerger

**Comment by bmann** [comment]
I’d like to see the AM be more reliable / have less intervention and document who and how to talk to someone if it goes down, so no one is a single point of failure. 

Are you open to this @Arachnid?

**Comment by Arachnid** [comment]
@bmann Sure! What did you have in mind, concretely?

**Comment by bmann** [comment]
Figuring out where to document this — maybe in the README for this repo? — and having st least two people who can “kick the automerger”. 

If we can improve it so it breaks less that would be good too.

**Comment by Arachnid** [comment]
Not sure what "kicking" it involves?

The only issue I'm aware of is a race condition; sometimes the automerger gets pinged by Travis announcing the build succeeded before Travis pings Github, and so fails to merge because Github doesn't yet know the build succeeded. I haven't found a good way around this; a kludgy solution would be to add a fixed delay before checking Github.

Anyone can prod the automerger to reconsider a PR by going to `http://ethlab-183014.appspot.com/merge/?repo=ethereum/eips&pr=1234`.

**Comment by bmann** [comment]
Great, thank you -- I think that's enough for anyone can prod their own PRs now!

I have documented this on a new Infrastructure page on the Ethereum wiki: https://en.ethereum.wiki/infrastructure

**Comment by Bormon007** [comment]
Sure

**Comment by axic** [comment]
Documented some of this in the readme with #1977.
