### ISSUE TITLE
Patent covenant for EIP submissions

### ISSUE THREAD

**Issue by bmann** [ethereum/EIPs#1840]
In several discussions about the EIP process, a concern has been raised about patent coverage.

Specifically, while the text of the EIP is contributed by the authors under CC0, this does not speak to whether or not they hold patents against it.

Do we need to add patent covenant language to the EIP process? Can we pay for a review and assistance from lawyers to help with this?

Please use the [EthMagicians forum](https://ethereum-magicians.org/t/patent-covenant-for-eip-submissions/2901) for long form discussion of this item.

**Comment by erkinalp** [comment]
What about this (GPL-like patent clause):
`The licensee is allowed to use, reproduce, build upon, build over, develop, the patented products and processes based on the description, drawings and claims of the given patents.`

**Comment by axic** [comment]
Wouldn't use a license which has specific clauses about patents work here? e.g. using Apache-2.0 or MPL-2.0 instead of CC0.

**Comment by bmann** [comment]
We can theorize, but we’ll need to get actual legal advice if we want to solve this.

**Comment by bmann** [comment]
Here's Bob Summerwill's suggested changes for ETC https://github.com/ethereumclassic/ECIPs/pull/162/files#

This looks pretty much like what should be adopted here.

And the same should be applied to ETH2 specs, too.

**Comment by MicahZoltu** [comment]
> We can theorize, but we’ll need to get actual legal advice if we want to solve this.

Lawyers also only theorize, they are just experts at it.  The job of a corporate lawyer is 99% trying to _guess_ how some future unknown judge would rule on some topic.  On the topic of copyright/patent lawsuits, there are actually relatively few cases that actually end up in front of a judge, so when a lawyer guesses about how a judge will rule on patents/copyrights they are largely extrapolating based on other related concepts that have made it to a judge.  Unfortunately, what is much more common than that is to just compare yourself to how everyone else does it and rely on the fact that "Google is a bigger target, and they do X, so if we do X we will likely be overlooked by the trolls".

> Here's Bob Summerwill's suggested changes for ETC https://github.com/ethereumclassic/ECIPs/pull/162/files#

That basically says "Satoshi Nakamoto is not allowed to contribute to this project."

----

The things that I would like to see remain for Ethereum regarding licensing/patenting process:
1. No attribution required.  While the vast majority of software engineers ignore the attribution clause in licenses, I would rather not have it in the first place.  CC0 is the most open license possible (on par with things like WTFPL and Unlicense) and allows the code to be used with the fewest restrictions.
2. Anonymity allowed and encouraged.  We live in an age where people are forced to give up more and more privacy every day.  I would like to see Ethereum continue to push back against that rather than capitulate to it.  I would rather see patent troll companies like IBM _not_ engage with Ethereum than drive away actors like Satoshi because we were unwilling to allow people to engage privately.
3. No additional work required by contributors.  It is hard enough to get people to contribute _usefully_ to EIPs.  Making them go through bureaucratic hoops like checking boxes before they are allowed to contribute doesn't encourage contributions, it only discourages them.

----

Something I would be amenable to is the addition of a PATENT.md file in the root of this repo and linked to by the EIP template if desired.  In this file it would just assert that the contributor waives patent rights of any code they contribute and to the best of their knowledge is not aware of any patents on their contribution.

**Comment by erkinalp** [comment]
4. Term exclusivity. While the licence should be non-exclusive, it should require all licensors and all licensees to be licensed under the same terms, i.e. prohibit parallel licensing schemes. If copyright holder licences different persons under different terms or tries to retroactively change the licence, he should get a contractual ban to use his own code, whilst retaining the validity of the licence for downstreams and upstreams.

This will facilitate the work of similarity checkers required to be used in academic circles and in European Union Digital Single Market Copyright enforcement.

**Comment by bmann** [comment]
@erkinalp this is mainly about the spec license and also about any sample code. Spec under CC0 is fine. 

Having sample code under Apache would mean that sample code is always under Apache and we’re good. 

@MicahZoltu I agree with most of what you’ve stated. Asserting / agreeing to a PATENTS.md might be the lightest weight thing to be done. And it’s frameable as a question - can pseudonymous contributors give up patent claims by contributing (or similar phrasing).
