### ISSUE TITLE
TRXID opcode

### ISSUE THREAD

**Issue by nmushegian** [ethereum/EIPs#222]
There are a number of interesting primitives that can be constructed if you can get a handle on the "current atomic interaction" aka "current transaction"

TRXID could be a simple increasing global nonce, or could be `sha3(origin,nonce)`. 

The closest you can get right now to a unique ID is `(origin,block)` plus enforcing one-origin-per-block which is awkward and incomplete.

**Comment by nmushegian** [comment]
Your very smart competitors "qtum" implemented this abstraction, can you handle being outsmarted @gavofyork @chriseth 

> – OP_TXHASH: This opcode is used to reconcile an odd part of the accounting
abstraction layer and pushes the transaction ID hash of a currently executed
transaction.

https://qtum.org/uploads/files/cf6d69348ca50dd985b60425ccf282f3.pdf

**Comment by jbaylina** [comment]
May be an OP_TXNONCE is better idea...  This way you can put a condition filled only when two consecutive transactions happen.

**Comment by dbrock** [comment]
>This way you can put a condition filled only when two consecutive transactions happen.

Interesting...

Maybe even just call it `OP_TXNUMBER`?

**Comment by Arachnid** [comment]
> There are a number of interesting primitives that can be constructed if you can get a handle on the "current atomic interaction" aka "current transaction"

Can you enumerate some of them?

**Comment by cdetrio** [comment]
One use case for this is the "asynchronous oracle pattern", alluded to in https://github.com/ethereum/btcrelay/issues/44 which discusses how REVERT + RETURNDATA can undermine synchronous oracles.

For an asynchronous oracle (i.e. oracle contract is first sent a payment and request for data, then a callback tx is sent to get the return data), the oracle contract needs to to ensure that the payment call and the callback call originate from different tx's. Otherwise, the payment call could be reverted after the return data is received.

Currently the only way for contracts to distinguish the transaction scope of two incoming calls is to check the block `NUMBER` or `BLOCKHASH` in each call; there's no way to distinguish whether two calls originate from a single tx or from two different tx's within the same block. A `TRXID` opcode would enable contracts to check that two different calls are from two different tx's, so that an oracle contract could securely allow both the payment tx and the callback tx to occur within the same block.

**Comment by nmushegian** [comment]
Had not heard of that example @cdetrio, that's great.

My main goal here has to do with tokens and allowing temporarily negative balances within a transaction

**Comment by vbuterin** [comment]
Personally out of all of the above I favor TXNUMBER. It's cleanest and simplest.

**Comment by jbaylina** [comment]
@vbuterin Should TXNUMBER be the index of the transaction inside the block?, or should it be a global index that does not starts from zero on each block and goes always incrementing?

**Comment by nmushegian** [comment]
I think global index is more useful, but `(blocknum, tx_in_block)` is also fine if anyone can think of reasons to care about per-block index

**Comment by SergioDemianLerner** [comment]
You can adopt RSK TXINDEX implementation, which is very similar to the one discussed here. You can check RSK's TXINDEX here:
https://github.com/rsksmart/rskj/blob/master/rskj-core/src/main/java/org/ethereum/vm/VM.java#L849

**Comment by nmushegian** [comment]
Hi github robot helper, no it looks like this is still not implemented but maybe a good suggestion! Thanks for the bump!

**Comment by MicahZoltu** [comment]
@nmushegian If you want to pursue this idea, you should either create an EIP following instructions in [EIP-1](https://eips.ethereum.org/EIPS/eip-1) or create a thread in the [Ethereum Magicians forum](https://ethereum-magicians.org/) to discuss it further.

Closing this for now as this repository is no longer the right place for discussions like this.
