### ISSUE TITLE
Discussion for E-signatures

### ISSUE THREAD

**Issue by james-chien** [ethereum/EIPs#2801]
I wanna discuss about E-signatures on smart contract and would like to get some feedback from you. I describe my idea and motivation spec below.
The following is not complete EIP draft. I will fix it while I get more feedback on my idea. Please feel free to comment about your thoughts.

**Simple Summary**
    A standard interface for e-signature.

**Abstract**
Electronic signatures have the same legal status as handwritten signatures. This standard provides basic functionality to securely track and record within smart contract. The signers can sign with their own signature and store it on the Ethereum blockchain.

**Motivation**
A standard interface allows signers to work on Ethereum. We provide document management as well as consent message while signing or before opening your document.
Enhance the security and assurance of electronic contract on the Ethereum blockchain by specifying standard interfaces through which contract can be signed and interrogated by all relevant parties.

**Specification**
    The following interface describes e-signature functionality. It has not yet submit as Github Pull Request, only for discuss purpose.

    interface ESIGNATURE {
      event Sign(address indexed signer, bytes32 indexed contractName)

      // e-sign
      function sign(bytes32 signatureHash) external;
      function signers() external view returns (address[]);
      function signatures() external view returns (bytes32[]);
      function period() external view returns (uint256);
      function parties() external view returns (uint256);
      function consentMessage() external view returns (string);
      function validContract() external view returns (bool);

      // Document
      function getAllDocuments() external view returns (bytes32[]);

      // Metadata
      function name() external view returns (bytes32);
      function issuer() external view returns (address);
    }

**Comment by MicahZoltu** [comment]
@james-chien I think in the Motivation section you should explain why this is something that needs to be standard rather than just a contract.  Interface standards are useful when you have a many-to-many relationship of people on both sides of the interface.  This means you have many different contracts that implement the interface, and many tools/contracts that make calls into a variety of those implementations and need to be able to interoperate with any of them.

A good example of a useful interface standard is a token interface, because there are thousands of tokens and probably just as many unique tools that benefit from being able to interop with *any* token (rather than just a specific token).

A good example of something that has no need for a standard is ENS.  There is a single ENS registry on Ethereum and there are *many* tools that integrate with it.  There is no standard for the ENS registry, instead it is just well documented and published publicly and anyone can integrate with it by reading the docs or code for it.

My first instinct is that this is something that would perhaps better match the ENS example than the token example, but maybe I'm missing something?
