### ISSUE TITLE
EIP 102 (Serenity): Rename "gas" to "mana"

### ISSUE THREAD

**Issue by vbuterin** [ethereum/EIPs#29]
To commemorate the increased environmental friendliness of proof of stake, starting from Serenity "gas" should be renamed to "mana".

### Rationale

Aside from the above, "mana" is a better descriptor because:

* Unlike "gas", "mana" is typically understood to be ephemeral and nontransferable, clarifying the relationship between ether and gas/mana that has so far been a source of great confusion.
* Gas in the real world is non-renewable, gas in Ethereum is renewable. Mana is typically understood to be renewable, and so would be more accurate.

### Implementation

     for x in `find .`; sed -i s/gas/mana/g $x

**Comment by taoeffect** [comment]
I think it's brilliant.

Fully support. :+1: 

Side-question: why the two order of magnitude jump in EIP numbering?

Side-comment: I love that EIPs have titles (unlike BIPs). Yay! :raised_hands:

**Comment by vbuterin** [comment]
0xx = pre-serenity  
1xx = serenity  
2xx = scalability or beyond  

is the schema that I am trying to put in place.

**Comment by JeffreyBPetersen** [comment]
Is that schema an EIPIP?

The switch from gas to mana sounds solidly justified for the small confusion it might cause.
It's also much catchier and a good thematic fit alongside "Ethereum".

**Comment by janx** [comment]
`mana_price` sounds a bit weird?

**Comment by vbuterin** [comment]
@janx luckily that opcode will likely be removed in EIP 101 entirely: https://github.com/ethereum/EIPs/issues/28 :)

**Comment by Smithgift** [comment]
Insert MTG reference here.

On a serious note, gas has a real-world analogy: you use oil (ether) to make a fuel (gas). I have a minor concern that this could cause confusion for the non-geek. ("Listen, the reason you're having trouble with your bingo dapp is you're out of mana. See, um, mana is...") That said, I agree with the idea.

**Comment by romanman** [comment]
@vbuterin, I have a small doubt, that mana has too much magical/mythical connotation associated with white wizards and flying unicorns, mostly understood by gamers rather than modern finance world. Dont you think we can have an adaptation problem?

**Comment by wanderer** [comment]
>associated with white wizards and flying unicorns

@romanman I think would help adaptation :)

**Comment by gavofyork** [comment]
"mana" may end up being shorted to the single-syllable, three-letter "MAN", which could result in accusations of gender bias...

**Comment by gavofyork** [comment]
i also agree with @romanman . i'm all for sci-fi references but "mana" just makes me think of sad 13-year-olds playing WoW in their pyjamas.

**Comment by Smithgift** [comment]
On the subject of other words for gas, "steam" both has a power connotation, works colloquially ("ran out of steam"), and also means, in a sense, ether.

**Comment by PeterBorah** [comment]
I am mildly opposed, on the argument that change is confusing and should be avoided unless necessary. People are going to look at old code and say, "What is all this 'gas' referred to?" Veterans are going to keep calling it gas out of habit, confusing newcomers. I don't think the mild semantic benefits of the switch are worth the "transaction costs".

**Comment by PeterBorah** [comment]
Changing "contract" to something like "agent", on the other hand, would definitely be worth it.

**Comment by Smithgift** [comment]
I dislike "contract" as a name myself, as it implies contracts are like financial contracts, when really they are more like World-Computer Programs.

**Comment by karalabe** [comment]
@gavofyork :+1: 

Mana might seem fun, but imho it would become an obstacle for people to take the project seriously. I'm all for dropping gas, but we should aim for something simple, elegant yes serious, neither of which can be said about mana.

**Comment by CJentzsch** [comment]
Something not funny would be "taxes". Basically paying tax to the miners in the ethereum world.
But what it really is, is a unit for computation time or storage on a super computer.
Might want to call it "Flips" , since every calculation as well as storing data is just about flipping some bits.
Ideally one "Flip" is exactly the cost of one bit flip :-) .

**Comment by obscuren** [comment]
:-1:

**Comment by LefterisJP** [comment]
Let's keep naming in a professional level. I don't see something wrong with Gas, and we want the ecosystem to grow and our technology to be widely adopted by many different sectors. Naming it "mana" won't help our cause.

**Comment by Gustav-Simonsson** [comment]
![resources_mana_410](https://cloud.githubusercontent.com/assets/293096/11320004/51ae0c90-908c-11e5-934e-866f142796db.jpeg)

**Comment by hughlang** [comment]
I'm sorry I don't agree. Gas is a functional term that is almost universally recognized. Newcomers hang onto the term "gas" because it is immediately obvious that it is a consumption fee tied to some work. 

Specialized insider terminology is counter-productive. "Mana" is like gold (gasp) or pixie dust.

Can we put this to a vote?

**Comment by rfikki** [comment]
My choice is to leave it as "gas" but, possible alternative choices could be: Petro, Energy, Toll

**Comment by taoeffect** [comment]
> "mana" may end up being shorted to the single-syllable, three-letter "MAN", which could result in accusations of gender bias...

That doesn't make any sense. Not an argument.

> i also agree with @romanman . i'm all for sci-fi references but "mana" just makes me think of sad 13-year-olds playing WoW in their pyjamas.

If ya'll have a problem with mana we can always go with stamina points.

**Comment by taoeffect** [comment]
> "Listen, the reason you're having trouble with your bingo dapp is you're out of mana. See, um, mana is..."

:laughing: oh man that is reason alone to do this. That is what I call a bright future.

**Comment by o0ragman0o** [comment]
Not a gamer so didn't know 'mana' had been appropriated by them...

This naming really irks me because of it's religious origin.  'Mana' of course was the food that biblical god Jehovah/Yahweh dropped on the ground every morning to the ancient Hebrew's to keep them alive for 40 year in the desert (or a least until they complained).

'Mana' == "What is it?" as they'd never seen it before.  

It came with rules...
1. Mana will be provided on Sunday to Friday.
2. Will turn to worms if not consumed on the same day as provided.
3. Manner will not turn to worms on the Sabbath (Saturday).
4. Collect double rations on Fridays as Sabbath must be kept holy and if you work I will likely kill you.

So unless you want a religious blockchain that takes Saturdays off, and where unused gas turns to worms the next day, I think calling 'gas' 'Mana' is a very bad idea.

I personally would prefer 'fuel' as it's a far more generic concept than the American colloquialism 'gas' (when everyone else calls it petrol or alike.)

So please, keep the blockchain agnostic.

**Comment by JeffreyBPetersen** [comment]
@o0ragman0o fuel has the added bonus of being largely synonymous with gas so as to not confuse people with the name change.

**Comment by LefterisJP** [comment]
And if gamers need gaming references for the term Gas ...
[Vespene Gas](http://vespene.ytmnd.com/)

**Comment by axic** [comment]
As others have mentioned it here or on reddit, mana too much feels like a game or a nerd thing. If it really needs to be changed, why not try to stick to computer science terminology, with something like ```cycle``` (from cycle count)? 

I do like gas however. Despite using PoS instead of PoW, computing happens anyway and that consumes energy.

**Comment by PeterBorah** [comment]
@o0ragman0o, that's "manna" with two "n"s. Mana is a term originally from Polynesia, and now used by gamers.

**Comment by mwilcoxnz** [comment]
I'm on the fence. Like others I agree it is associated to gaming, but I think it can fit nicely into the rest of the Ether branding and get past that. Most people involved with ethereum are probably not the best sample as most of us associate it more heavily with games than the actual meaning behind the term. Gas does make sense in a PoW world but I think mana does have a more positive connotation especially in a PoS world. Long term I think it would work. One thing to remember is that ether is the main user-facing token and gas / mana is more developer oriented.

Re @PeterBorah's thoughts on contracts, I think agents *are* too nerdy / technical compared to contracts, much more so than gas / mana. With contracts there's a very clear link between the name and function of the thing, whereas the tradeoff between the more functional name of 'gas' and the more idealistic name of 'mana' is easier to make as gas isn't so easily paired with the functionality in the first place.

**Comment by taoeffect** [comment]
>  Long term I think it would work. One thing to remember is that ether is the main user-facing token and gas / mana is more developer oriented.

:+1: 

This will be a developer facing thing, not a user-facing thing. Most people will never be exposed to it, so "branding" concerns are mostly unfounded, IMO. The devs, on the other hand, get to have all the fun. :smile:

**Comment by Smithgift** [comment]
I don't think gas can be a purely developer-facing thing, because gas price is at some point a user decision. This may boil down to a single slider somewhere deep in mist that is rarely touched, but it's going to inevitably leak out of the realm of abstraction those rare times.

**Comment by taoeffect** [comment]
@Smithgift, can you give an example where mentioning anything but the cost of the txn (in terms of Ether or a subcurrency) would be required for the average user?

**Comment by Smithgift** [comment]
@taoeffect: Suppose I want my transaction to be confirmed faster, or I'm poor and want it cheaper. I don't see how I can *not* hear about gas price without my client being disingenuous. It could tell me, "Hey, if you want it confirmed within ~60 seconds with %90 probability you'll pay X ETH total," but it would be wrong, because the actual final cost to a transaction is indeterminate short static analysis.  

In fact, I don't think we can "hide" total gas, either, because how does the DApp explain what happened when the transaction failed due to running out of gas?

**Comment by taoeffect** [comment]
> In fact, I don't think we can "hide" total gas, either, because how does the DApp explain what happened when the transaction failed due to running out of gas?

Uh... you say more Eth is needed. That's what they're paying in.

No need to talk about gas or mana. Why would you want to confuse the user with this junk?

It would be like saying, "Dear Bitcoin user, the block size limit is 1MB and so your transaction didn't make it in"... just absolutely silly, horrendously pointless UI/UX.

There is a transaction fee. Increase the fee. No need to talk about block size!

**Comment by koeppelmann** [comment]
+1 for too high "transactions costs" for too less benefit. Already the renaming of uncles to "ommer" did not work.

I always have the feeling that such discussions are incredible ineffective. I would be a big fan of a arguments-tool where you can visualize and vote for arguments. Unfortunately I guess there is not a good tool for that - the best I found was this - just for fun I tried to capture the debate: http://en.wikiarguments.net/should-we-rename-gas-to-mana/

P.S. I also started a market: http://groupgnosis.com/dapp/#/markets/0x713387538cf04676bb5d9c9d904ed87a/0x1878ace4203099dfa8838bbf2db86b5e9d364fba0

**Comment by taoeffect** [comment]
Voting also taking place on the subreddit: https://www.reddit.com/r/ethereum/comments/3trxzk/poll_eip_102_rename_gas_to/

**Comment by o0ragman0o** [comment]
@PeterBorah,  thanks, I didn't know that.  Though I think it illustrates further what an obscure notion 'mana' is.  'Gas' is a pretty intuitive concept and I don't see any benefit in changing it just because it's 'renewable' in Ethereum.

**Comment by ErikBjare** [comment]
Changing basic terminology this late would likely only be a cause for confusion. Unless the basic mechanism of gas is about to change the name should remain the same. Some minor symbolism about mana being renewable while gas is not is a pretty weak argument in my opinion.

**Comment by etherReal** [comment]
@vbuterin @romanman :+1: to "mana",  
Though @ErikBjare @koeppelmann and otheres object to changing the language because we are used to it; I think it is still VERY EARLY days and the number of Ðevs and users yet to come will benefit from mana far more than we will lose in dropping gas.  

It's easy to get stuck in an English Language 'bubble', where 'Mana' has a little gamer and biblical fuzz, but that may be no bad thing for Christians and Gamers.  The only negative meaning of Mana I know is from Buddhist thought where it is the cause of pride and conciet.   But like @PeterBorah pointed out in most  mythologies where it shows up [Pacific Island / Polynesian / Anglo-Saxon] it is "a force altogether distinct from physical power ... which it is of the greatest advantage to possess or control" or "life-force / charisma" or (my favourite for it's mythic implications in ethereum) 'Mana mutra'  which is the practise of drinking ones own urine. :smile: after that is kind of what is going on :8ball:

**Comment by Smithgift** [comment]
@etherReal 

Speaking as a gamer (idle game running in background) and a Christian (holy card and rosary in pocket, image of Divine Mercy under monitor) I don't have a problem with the term qua term personally. Though the arguments against changing anything have more and more convinced me in favor of gas remaining "gas".

**Comment by Smithgift** [comment]
@taoeffect 

The Bitcoin block analogy isn't quite accurate, because if my bitcoin transaction takes three blocks to get in or twelve it doesn't matter much to me. Whereas running out of gas costs me something, gains me nothing, and if what I was trying to do was time sensitive I may have lost the opportunity. A better Bitcoin equivalent would be the tx being dropped altogether due to a [crash landing](https://medium.com/@octskyward/crash-landing-f5cc19908e32) scenario, at which point the user has a legitimate demand to know what is going on.

An alternate analogy would be a car. There are, if you will, multiple levels of car knowledge.

1. How to actually drive the vehicle.
2. How to own a car (maintenance, registrations, buying gas)
3. How a car actually works, down to the physics of internal combustion engines.

Theoretically, you only need a level 1 knowledge of cars to actually use one, whereas the manufacturer of the car needs level 3 knowledge. It is reasonable to leave out a lecture on the mechanics of the car for the buyer, but level 2 knowledge is important.

To bend the analogy even further, if driverless cars were popular, manufacturers could simply make an interface where the user selects destination and speed and the car takes care of everything, down to calculating the fuel required and buying it when necessary. But then if the car runs out of gas due to some unexpected situation, the passenger is now stuck. Had the passenger specifically ordered more gas by an informed decision (say, knowing there will be heavy traffic) the passenger might have avoided it.

"Proof by analogy is fraud," to quote Bjarne Stroustrup, but I think ethereum gas price falls on the border of level 2 and level 3. It's if it moves into level 2 that we have the problem.

Actually, the last time I read a microwave manual, it included a brief description of the principles behind microwaves and their history. It's not unreasonable to assume that the user will ask a few questions about how their client works, at which point we will be unable to hide the existence of gas. Or even if we make an infographic to describe Ethereum to an interested outsider.

On that same subject, consider how few of the people affected by Heartbleed actually knew/cared/had the background to understand why they needed to change their passwords, but they did have to change their passwords nonetheless. In some severe network crisis (spam attack?) gas is going to become important enough for the user to car about.

**Comment by aakilfernandes** [comment]
I think both "mana" and "gas" are off base. What is being described is closer to a "delta". Its a change in the state of the system or a computation required to make that change.

A "delta price" makes it very clear what you're trying to describe. Its the price of making every node in the system execute one delta.

**Comment by aakilfernandes** [comment]
However agree with sentiments above that this is not really a user facing term, so the status quo is fine.

**Comment by taoeffect** [comment]
@Smithgift 

> A better Bitcoin equivalent would be the tx being dropped altogether due to a crash landing scenario

Did you just link me to a Mike Hearn post? lol, I believe you did.

**Comment by taoeffect** [comment]
Seriously, if Mike Hearn's BS can infect the Ethereum community too, well, I think I'm going to have to quit the software business, because it will be a clear sign that humans lack the sufficient critical thinking to handle computers.

**Comment by taoeffect** [comment]
Folks will have to forgive me for my flipping responses above. I've already spent an extraordinary amount of energy on this topic elsewhere, and as you know the bs asymmetry principle works against you:

![bullshit amount](https://cloud.githubusercontent.com/assets/138706/11328238/2f4caae4-913b-11e5-9224-c251dba22db2.jpg)

**Comment by Smithgift** [comment]
I apologize if I appeared to be making any kind of passive-agressive snark; I had no knowledge you were involved on either side of the blocksize debate.

Please, let's just ignore all this and get back to renaming (or not) gas.

**Comment by taoeffect** [comment]
> Please, let's just ignore all this and get back to renaming (or not) gas.

Agreed. :+1: 

FYI, on [reddit](https://www.reddit.com/r/ethereum/comments/3trxzk/poll_eip_102_rename_gas_to/) Gas is in the lead by a lot, but a late contender not discussed here—Lux—has overtaken Mana.

**Comment by etherReal** [comment]
:+1: Lux @taoeffect 

and Another thought.  
Language is a natural consensus system.  Words and names get coined all the time and people constantly  [exapt](https://en.wikipedia.org/wiki/Exapt) and adapt words from one place to another.  We just use the words that come to mind first, which is why it seems to cost so much to "re-brand" a meme, when you get your mucking words fuddled.  

No matter what last years dictionary says a word means what your audience believes it means.  I'm going to start using the word lux instead of gas and see where that gets me :- Which won't be far unless I'm part of a big enough memeing  pool.  Let's get Lux over 51% until it hits :100:

**Comment by alexvandesande** [comment]
While I liked the concept of mana at first I agree that it doesn't really help the general public understand it. The same can be said of "lux", unless you are an astrophysicist or a lamp engineer, it's a term you've never heard about.

The real problem with gas, is that it's not understood as a real unit. You don't put 10 gas on your car, you put 10 **liters** of gas on your car. The idea of measuring gas in *gas units* is rather confusing to the user.

On the wallet we might simply use the term *transaction cost*, *execution price* or a more declarative term and avoid any unit names whatsoever.

**Comment by tymat** [comment]
![magic](http://i.imgur.com/8m6exb8.jpg)

**Comment by goodtaster** [comment]
This is such a terrible, alienating and manbaby-centric proposal that I honestly think Vitalik may be developmentally disabled

**Comment by etherReal** [comment]
@tymat LOL
 @alexvandesande - Yes to gas is not a unit of measurement.  
with Lux you get to talk about lumens which *is* a unit of measurement.  
I agree that this is not a "User facing" issue but if they look under the hood (which many many will if the media conversation about Bitcoin is anything to go by) then it would be nice to find a metaphor there that was less "dirty" than Gas.
If you ever wanted to make lux consumption a UI feature A Ðapp could show off the Lux consumption with a simple scale from candle to star or whatever.   I don't think there is as easy an icon for gas unless you have a miles per gallon scale or something.

**Comment by robertandrewsmith** [comment]
I think we still have a tendency to describe ether as a crypto fuel, not a store of value. And although it could be both, stating that we're sending some object, "gas" which is ether confounds the problem. Ultimately, gas is an object collected as a fee. However, the transformative ability of state, and dynamic notion of code execution is the core functionality of the Ethereum protocol. So the term ought to be more accurately descriptive.

Fuel is a good word, because like "refilling", we can "fuel" or effectively "refuel" our contracts. I'm also fine more generically terming ether gas as "power". You can power your contract with ether. Therefore send ether power.

Anyway this is pedagogy. Ether is gas. But gas is not ether. Gas is fuel and gas is power. Imagine branding "Powered by Ethereum", "Fueled by Ethereum", "Ether: Power for Smart Contracts", Ether: Fuel for Smart Contracts".

Now compare: "Ether: Gas for Smart Contracts"? "Ether: Petrol for Smart Contracts"? "Ether: CO2 for Smart Contracts" "Ether: Biofuel for Smart Contracts", "Ether: Lux for Smart contracts", "Ether: Mana for Smart Contracts"

"Fuel" and "Power" is infinitely a better term.

**Comment by aakilfernandes** [comment]
> The real problem with gas, is that it's not understood as a real unit. You don't put 10 gas on your car, you put 10 liters of gas on your car. The idea of measuring gas in gas units is rather confusing to the user.

:+1: @alexvandesande 

This is similar to what tripped me up when learning about gas.

**Comment by Phistr90** [comment]
:-1:  Are you sponsered by Magic the Gathering? First the Ethereum Logo:
https://en.wikipedia.org/wiki/Zendikar

Now rename Gas to Mana... :D

**Comment by etherReal** [comment]
@Phistr90 so if we follow the algorithm gas should be called auaw <--(supposed to be the word mana inverted )

**Comment by twigwam** [comment]
I bel

**Comment by christianlundkvist** [comment]
Opposed to this. I think Gas is a good, neutral term and perfectly describes its use.

**Comment by skmgoldin** [comment]
I like gas over mana.

**Comment by ethers** [comment]
Agree with most of the reasons for Gas.  It's much clearer than alternatives like mana or lux.  When should this EIP get closed? ;)

**Comment by bobsummerwill** [comment]
Please no.

**Comment by hughlang** [comment]
Also no.

Yes, Ethereum is special, but it does not need a special lingo that only insiders might enjoy, but is otherwise counterproductive.

The term "gas" has utility value in the same way that something is has value because of its usefulness. Hence the metaphor: if Bitcoin is like gold and Ethereum is more like oil/gas. Maybe not perfect, but still has some meaning.

Who can make the call to close this issue?

**Comment by obscuren** [comment]
Done

**Comment by vokkantthakkar** [comment]
Can we reconsider this?

**Comment by cryptofelon** [comment]
Requesting reconsideration.

**Comment by 0xfoobar** [comment]
hello, ESG is very important to me, I would never use any petroleum products (except for my iPhone and fast food microplastics), I have glued myself to the Ethereum mempool in protest until the name for gas is changed to mana

**Comment by tenacity-eth** [comment]
It's time.

**Comment by LefterisJP** [comment]
+42

**Comment by iFrostizz** [comment]
lgtm

**Comment by Pandapip1** [comment]
If any of you would like to make this an EIP, please open a thread on [FEM](https://ethereum-magicians.org/).

**Comment by Ceazor** [comment]
I can just imagine the mana bars and mana potions (gas rebates)

**Comment by s1dedoteth** [comment]
It is worth noting that the term "gas" in Ethereum is already well-established, and changing it to "mana" could cause further confusion among those already familiar with the Ethereum network. Additionally, "gas" is a term used in other blockchain networks and in computer science more generally, so changing it to "mana" within the context of Ethereum would not be in line with the broader usage of the term.

**Comment by intldds** [comment]
"mana" is such an elegant/brilliant name, let's go

**Comment by pcaversaccio** [comment]
Ok, I did it :-D - the FEM link: https://ethereum-magicians.org/t/rename-gas-to-mana/13570.

**Comment by Pandapip1** [comment]
Since there's now a discussion link on FEM, I'm going to lock this issue.
