### ISSUE TITLE
EIP-2980: Swiss Compliant Asset Token

### ISSUE THREAD

**Issue by alanscarpellini** [ethereum/EIPs#2983]
A place to discuss PR [EIP-2980](https://github.com/ethereum/EIPs/pull/2980).

**Comment by enehizy** [comment]
In my opinion eip1559 is somewhat similar to bitcoin's security model, the bitcoin block reward halfs and eventually it goes to zero and the miners depend solely on transactions fees,in ethereum with eip1559 it's flipped this time it's transaction fees that are burnt and miners depend on block rewards and tips from users..eip1559 is our own version of bitcoin halving..adapted to ethereum security and economic model

**Comment by MicahZoltu** [comment]
@enehizy This isn't the right place to discuss EIP-1559.  Please use the discussions-to link at the top of https://eips.ethereum.org/EIPS/eip-1559

I will delete this message and yours after sending this in hopes that you have email notifications enabled.

**Comment by thedavidmeister** [comment]
hi, i've been working on similar things in and around europe recently so i'm glad to see the potential for some kind of standard

most of the logic around whitelist vs. frozen i believe i can incorporate fairly easily as it is very similar to what i have already done

i do have some feedback:

1.

having a single "issuer" role seems unnecessarily broad and centralizing in nature, although i appreciate that the singular issuer address could be handed to a smart contract that implements its own fine grained access control.

would it make sense to separate the ability to manage the white/frozen lists from the ability to directly handle funds?

in this scenario i would expect that ONLY funds on the frozenlist can be revoked/reassigned, which could hamper an attacker as they would need to compromise BOTH a freezer and a revoker account in order to arbitrarily move funds to themselves.

in this scenario i would also expect that funds that were delisted from the whitelist but still held are NOT able to be revoked/reassigned. To me this intuitively seems more true to the stated intention of having frozen and whitelisted funds as separate concepts, where the latter still allows assets to be owned by the holding address until they dispose of them.


2.


i also see the monolithic "issuer" role as a potential misnomer as nowhere in the spec (if i read correctly) is it required that the "issuer" issues (mints and/or distributes) anything. The only privileges that an "issuer" has are the rights to _remove_ access to assets.

3.

lastly i am concerned that the methods that _write_ to the whitelist and frozenlist are specified at the interface level.

for example, i have implemented contracts that are compatible with the concept of being a white/frozen list externally to the token itself, which allows for:

- combining several lists AND/OR style into a single list to support e.g. multiple parallel KYC backends each with their own admins
- additional bytes of data to be submitted alongside adding/banning/removing users from the list that are emitted in event logs for offchain audit history
- several layers of access control around admins/executors of various KYC style operations beyond a single add/remove function (e.g. i distinguish between being a known-bad agent flagged as "banned" onchain and being completely removed from contract storage)
- batch modifications which can be important for gas efficiency given the potential for very large lists (thousands or tens of thousands) to be managed, perhaps the main list is managed offchain oracle-style and only synced periodically onchain, or even synced from another network occasionally

there's probably a lot of other things implementations might want to do with complex approval workflows that a single `address -> bool` function on the token itself can't represent efficiently

given that the existence of some way to write to the white/frozen list is implied by the read functions in the interface, i'm personally not sure that writes need to be specified

if there's a strong desire to keep and specify the write interface, then could the read and write interfaces be split with the write interface being an optional extension of the read interface?

**Comment by gavbrennan** [comment]
Hi, this seems to be closed for a while but still appears as in review on the page https://eips.ethereum.org/EIPS/eip-2980. Can anyone point to the legislated requirement that the tokens must be indivisible / have zero decimals?  Seems a big miss on the financial inclusion front, many brokers offering fractional investment these days.

**Comment by Chrissykay** [comment]
Yes I see hide the tokens really

**Comment by MDStone1993420** [comment]
@Chrissykay `string`cc+ pament never fail action 🍑
