### ISSUE TITLE
ERC-3000 discussion

### ISSUE THREAD

**Issue by izqui** [ethereum/EIPs#3042]
ERC-3000 presents a basic on-chain spec for contracts to optimistically enact governance decisions made off-chain.

The standard is opinionated in defining the 6 entrypoint functions to contracts supporting the standard. But it allows for any sort of resolver mechanism for the challenge/response games characteristic of optimistic contracts.

While the authors currently believe resolving challenges [using a subjective oracle](https://aragon.org/blog/snapshot) is the right tradeoff, the standard has been designed such that changing to another mechanism is possible (a deterministic resolver like [Optimism's OVM](https://optimism.io) uses), even allowing to hot-swap it in the same live instance.

### [Read more](https://github.com/ethereum/EIPs/pull/3000/files)

**Comment by BradleyLaytonPhDPE** [comment]
Not sure where the oracle discussion stands, but I am interested in developing oracle-based smart contracts for managing escrow for IoT-based energy management systems and implementing them via ERC20 or another appropriate mechanism.

**Comment by MicahZoltu** [comment]
Since this EIP has become stagnant, we are closing this discussion issue for housekeeping purposes.  You may continue discussion here on the closed issue (it won't be locked), but if you want to revive the EIP (bring it back to Draft or Review status), you will need to create a thread over at https://ethereum-magicians.org/ and update the discussions-to link in the EIP to point there instead (that is where all discussions happen now).
