### ISSUE TITLE
Accomplish a call or transfer in a pre-determined future time

### ISSUE THREAD

**Issue by vporton** [ethereum/EIPs#3043]
There should be an Ethereum "operation" to accomplish a call or transfer in a pre-determined future time (or block number).

By analogy with a well known ERC-20 approve vulnerability my method needs to be first called with a small (or zero) value and as soon as the transaction confirms with the new value.

The method is called by DAO accordingly voting. So the voting needs to set the value to zero (or small) value and after it is mined, anyone should be able to call the method again with the intended value (it is easy to make it callable by anyone by setting a boolean flag that removes `require()` checking the sender).

But if the organization is small, it may happen that calling it by anyone may be forgotten. Thus comes calling it in the future automatically.

It should be built-in into the blockchain rather than done by an external Web2 service for the clear reasons of reliability. (Also it would support settings arbitrary `msg.sender`, not the account of a third-party Web2 service.)

Need to store an enough value for gas beforehand. What to do with excess gas? return to the method sender after method invocation? donate to validators? burn?

**Comment by vporton** [comment]
Remaining gas should be returned to the sender: it allows him to send a big amount to be sure it will be enough for gas.

**Comment by vporton** [comment]
Need to deal something then with a million or more transactions happening at each 00:00 1 Jan. Any ideas?

**Comment by vporton** [comment]
There should be also "future external contract calls": if a voting ends preliminarily, my voting contract needs to wait a few minutes and then send one more transaction.

**Comment by vporton** [comment]
> There should be also "future external contract calls" (and "future .send()/.transfer()"): if a voting ends preliminarily, my voting contract needs to wait a few minutes and then send one more transaction. Where the returned gas should go in this case?

Additional proposals: external calls/transfers from contracts to be called after the current block is mined (is it possible to determine if a block is mined from inside a blockchain?), also canceling/changing such calls (for this need to store their IDs: either sequential or random).

Remember the original issue: We need to call a contract after the previous call would have been mined!

**Comment by MicahZoltu** [comment]
Transaction propagation becomes tricky when a transaction is not valid now, but may become valid later.  Timestamp based validity has the nice property that transaction validity change is predictable, and nodes can choose to only propagate transactions that have a validity transition within a certain time frame, so I don't think this is an impossible request.  However, that aspect is likely what will need the most thought.

If instead you are talking about having time-based triggers on executions that don't have an associated transaction, things suddenly become a whole lot more complicated.  You have to address the fact that gas costs may differ between when the transaction was sent and when the transaction executes (or finishes executing).  You also need to deal with figuring out the gas cost of storing that data indefinitely (until the triggering event occurs) and you can't just let individual nodes drop that data because it is part of state.  You also will need to figure out how the concept fits into stateless Ethereum, and how that data is synced.

**Comment by vporton** [comment]
> Transaction propagation becomes tricky when a transaction is not valid now, but may become valid later. Timestamp based validity has the nice property that transaction validity change is predictable, and nodes can choose to only propagate transactions that have a validity transition within a certain time frame, so I don't think this is an impossible request. However, that aspect is likely what will need the most thought.

No idea what you mean.

> If instead you are talking about having time-based triggers on executions that don't have an associated transaction, things suddenly become a whole lot more complicated. You have to address the fact that gas costs may differ between when the transaction was sent and when the transaction executes (or finishes executing). You also need to deal with figuring out the gas cost of storing that data indefinitely (until the triggering event occurs) and you can't just let individual nodes drop that data because it is part of state. You also will need to figure out how the concept fits into stateless Ethereum, and how that data is synced.

That the gas price may differ was addressed by me above: The sender should lend a big amount of ETH to pay for gas to the network at the time of sending transaction. All Ethereum state is store indefinitely, so no need to do something special about gas here. No idea about stateless.
