### ISSUE TITLE
EIP: another method to pay gas with tokens directly

### ISSUE THREAD

**Issue by acvrp-lab** [ethereum/EIPs#3059]
### Preamble
Title: pay gas with tokens directly
Author: Xu (@acvrp-lab)
Type: Standards Track
Category: ERC
Status: Draft
Created: 2020-10-19
Requires: ERC20
### Simple Summary
Allow mining node to accept a list of standard tokens of its preference as gas fees.
Allow user to pay from a list of standard tokens of its preference as gas fees directly.
### Motivation
I'm a newbie in the crypto industry, learning all kinds of new concepts. meta transaction, GSN(gas station network), smart wallet, DAI's gasless wallet, all to solve one problem - to pay gas with tokens. however, they add quite much complexity, security concerns, user need to pay extra reward to incentivize relayers.
So how about a client patch to allow gas fees to be payed with tokens directly?
### Specification & Implementation
This seems to be quite out of reach of a newbie's ability.
However, to my assumption, there's no need to fork, change anything to the chain mechanism, evm or other big components.
1. token contract patch to allow miner to transfer token at user specified gas price
2. mining node client patch to accept tokens of its preference
3. wallet apps(i've only used metamask till now) patch to allow user to pay with tokens just like how they pay with ether

if this proposal is ever impelemented, I assume stablecoins will become the most used paying tokens

**Comment by acvrp-lab** [comment]
after some thought, i assume i've come up with an implementation with the most backward compatibility.
### 1. paying token contract need to add one function. below is some pseudo-code
```
function gasless(address to, data, price-in-token) {
  var limit = gasleft();
  make-original-transaction{value: msg.value}(to, data);
  transfer(block.coinbase, (limit - gasleft() - extra to execute this line) * price-in-token);
}
```
an old transaction is a serialized message of {nonce, gas price, gas limit, recipient, value, data, sig A}
a gasless transaction is now {nonce, gas price=0, gas limit(a little bigger than previous), recipient=paying token, value, data =call to new gasless function, sig B}

### 2. mining node client:
old ones will still work, and can verify gasless transactions with no problems. only that it has nearly no chance to process 0 gas price transactions. if it does, it will receive fee in token just like updated clients.
updated clients will process gasless transactions just like old style transactions, compare gas price in ether/token, prioritize their prefered transactions. the more updated clients, it is more likely gasless txs will be processed.

### 3. wallet apps:
even old ones can run with some work from user or dapp developer, it is better to update for better user experience.

**Comment by acvrp-lab** [comment]
@vbuterin @opengsn @mosendo
sorry to bother you guys, but i think my solution is way much better/simpler than other complex ones, those involving meta transaction and relayer network

**Comment by MicahZoltu** [comment]
There are several solutions currently proposed that would enable people to pay for transactions with something other than gas.  One thing we want to be careful of is enshrining ERC20 tokens into the core Ethereum protocol, since it means we'll never be able to move past them in terms of technology.

Also, keep in mind that if EIP-1559 is merged (which continues to look more and more likely), then ETH **MUST** be burned as part of every transaction if there is any congestion.  This means that even if the miners did accept some other token as the miner bribe, someone would still need to burn ETH for the transaction to get included.

Check out https://eips.ethereum.org/EIPS/eip-2711 and https://eips.ethereum.org/EIPS/eip-2938 and https://eips.ethereum.org/EIPS/eip-2733 for some alternative proposals that may enable different mechanisms for gas payments.
