### ISSUE TITLE
ERC-721 and ERC-1155 to ERC-20 Wrapper

### ISSUE THREAD

**Issue by ashrowz** [ethereum/EIPs#3384]
The following is a proposed EIP to wrap ERC-721 and ERC-1155 tokens with ERC-20. It will be submitted as a Draft once it has been revised according to community feedback. Questions of implementation are contained in Rationale.

The pull request is open here: https://github.com/ethereum/EIPs/pull/3386

**Comment by Tuneabq** [comment]
This is the original Matthew George Lujan I am ERC-721.  NOW WHAT DO YALL SAY ITS TIME TO HAVE SOME FUN or WHAT?!!! Aka Tune.

**Comment by Tuneabq** [comment]
Are y'all ready for this bigger, brighter, broader, more intuit life cuz this is IT the SHIT!  Now we can make it happen, I just need all of you on my side.  Believe me I'll start working on a generator that generates ($cash money$) so that everyone will get up.  I have a lot of ideas for our future.  It's time that we start building up platforms. #Infinite 369 #infinitiM45 #Tune-up #TuneAbq  #WBTC #Eth #MusicIsLove #Gitrdunn

**Comment by MicahZoltu** [comment]
Since this EIP has become stagnant, we are closing this discussion issue for housekeeping purposes.  You may continue discussion here on the closed issue (it won't be locked), but if you want to revive the EIP (bring it back to Draft or Review status), you will need to create a thread over at https://ethereum-magicians.org/ and update the discussions-to link in the EIP to point there instead (that is where all discussions happen now).
