### ISSUE TITLE
Contract autobounce funds

### ISSUE THREAD

**Issue by fivedogit** [ethereum/EIPs#34]
(An idea I've had for a while, also spoken of by chriseth at DEVCON1.)

Right now, contracts default to accept all incoming funds, only returning or forwarding funds if specifically coded to. This creates a situation where the creator either has to code most methods to return funds or just accept that "mistake" funds will be sent periodically and add a "drain funds" method to recover them. 

Shouldn't a developer be able to specify "autobounce" at the contract level to change invert the current default behavior? In this situation, the coder would have to include an "accept offered funds" line in the code at each appropriate location, but in practice, that'll end up being far few times than returning funds in all error scenarios.

**Comment by chriseth** [comment]
We are currently planning to add special modifiers in Solidity (one for "don't send ether with this call" and one for "send at least x ether with this call") and having the compiler issue a warning if none of them is present.

**Comment by vbuterin** [comment]
When we add the abstraction features in [EIP 101](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-101.md), it will likely inevitably change the functionality so that contracts have to explicitly accept ETH transfers just like they have to accept subcurrency transfers if you use the cheque mechanism; this is basically equivalent to an autobounce flag that is on by default.

**Comment by axic** [comment]
@fivedogit Solidity >0.4.0 contains this feature named `payable`. By default, methods receiving Ether will throw and there's no default fallback either. Functions (incl. the fallback) marked `payable` can receive Ether.

I suggest to close this issue, unless there's a proposal to include such a feature on the EVM level.
