### ISSUE TITLE
Proof of storage

### ISSUE THREAD

**Issue by vporton** [ethereum/EIPs#3437]
PoS is a failure [1]. The model in [1] is certainly oversimplified but it looks like something similar can happen in reality rendering a PoS blockchain useless in a short time.

The main problem with PoW is it's carbon footprint.

So, not PoW, not PoS, but proof of space (aka proof of storage) should be the future Ethereum.

Somebody write an EIP.

[1] Houy, N (2014) “It will cost you nothing to “kill” a proof-of-stake crypto-currency” Economics Bulletin, Vol. 34, pp. 1038-1044.

**Comment by vporton** [comment]
Well, PoW has low throughput and proof of storage probably (I am not an expert.) also has throughput as low as PoW.

That is not a big problem. We can just use proof of storage mainnet and PoS sidechains/shards like Nervos.

**Comment by greenlucid** [comment]
The paper is absurd. 2 citations with no relevance.
The assumption the paper makes is that, because the other agents know agent 0 want to destroy the chain, then they lower the price until the cost of each unit reaches 0.
How entitled must the author of that paper be to believe he found the single best strategy of that system, fitting one page? You don't prove anything by stating it.
There are Proof of Stake chains that have no succumbed to that golden metagame. xDAI comes to mind. I suggest closing this issue. If you want someone to write a Proof of Space EIP for you, you can go to ethereum-magicians forum and discuss it there
