### ISSUE TITLE
Why does the following error occur in 0.5.+ version?

### ISSUE THREAD

**Issue by TongOS** [ethereum/EIPs#3615]
browser/Math.sol:6:28: SyntaxError: This looks like an address but has an invalid checksum. Correct checksummed address: "0x1Ff4a380391D029dBc981e7Eb347d652B094C6dC". If this is not used as an address, please prepend '00'. For more information please see https://solidity.readthedocs.io/en/develop/types.html#address-literals
    address addr = address(0x1Ff4a380391d029dBC981E7eB347D652B094c6dc);
                           ^----------------------------------------^

**Comment by abcoathup** [comment]
Hi @TongOS,

If you have questions about using Solidity, you can ask in a developer focused community such as CryptoDevs Discord (see link in their subreddit: https://www.reddit.com/r/cryptodevs/) or https://forum.soliditylang.org/

The compiler error explains what the problem is, you are providing an address but its checksum fails (see https://solidity.readthedocs.io/en/develop/types.html#address-literals).  You need to use an address with a correct checksum. 

Please check your address again.  Etherscan will give you an address in checksum format.

**Comment by TongOS** [comment]
> Hi @TongOS,
> 
> If you have questions about using Solidity, you can ask in a developer focused community such as CryptoDevs Discord (see link in their subreddit: https://www.reddit.com/r/cryptodevs/) or https://forum.soliditylang.org/
> 
> The compiler error explains what the problem is, you are providing an address but its checksum fails (see https://solidity.readthedocs.io/en/develop/types.html#address-literals). You need to use an address with a correct checksum.
> 
> Please check your address again. Etherscan will give you an address in checksum format.

First thank you very much for your response~ But my address copy from the Page that is  http://remix.ethereum.org/#optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.4+commit.c7e474f2.js.  The address is from the Page content "account".  The address is correct turely. I think this is a bug. Can you reproduce and fix it？Please~~
