### ISSUE TITLE
Native flash minting (in progress)

### ISSUE THREAD

**Issue by jessielesbian** [ethereum/EIPs#3850]
Native flash minting allows ETH, the native cryptocurrency of Ethereum, to be flash minted. Native flash minting addresses the gas intensity of other alternatives like wrapped Ethereum flash loans and allows flash minting past the normal Ethereum total supply.

Native flash minting will introduce 2 new EVM instructions: `FLASHMINT (0xb3)` and `FLASHBURN (0xb4)`. The `FLASHMINT` EVM instruction would increase the debt counter and mint ETH to the current account, while the `FLASHBURN` instruction would decrease the debt counter and burn ETH from the current account. If the smart contract call returns with a non-zero debt counter, `FLASHMINT` running into a balance overflow, or if the amount being burned by `FLASHBURN` exceeds the debt counter and/or the account balance, the EVM will revert the execution.

Native flash minting saves gas by not having to call other smart contracts for flash loans, which can make capital-free arbitrage in decentralized finance more profitable.

**Comment by poojaranjan** [comment]
Hi @jessielesbian, 

I am trying to understand the purpose of this issue. If this is created to share an idea, which if receives enough support will be proposed as an EIP to be an Ethereum standard eventually. Then, I would like to bring some recent changes in the process to your attention that we're trying to suggest to new proposals.

It is highly recommended to create a discussion thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/) (FEM) instead of "Issue" of this repo and add that FEM link to the proposal in "Discussions-To" section. 
This helps increase visibility by Ethereum devs and also has the history of discussion in a single place that could be easily referred to even after the proposal is "Final".

This seems to be the beginning of the discussion, hence maybe the best time to consider opening the discussion thread at FEM and close this issue. However, if I misread the purpose, please ignore this comment.

**Comment by axic** [comment]
Since you opened the issue https://ethereum-magicians.org/t/native-flash-minting/7053, can this be closed here?
