### ISSUE TITLE
[EIP-725] Upgrade

### ISSUE THREAD

**Issue by YamenMerhi** [ethereum/EIPs#3857]
## Abstract
Upgrade for the current [eip-725](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-725.md) .

## Motivation
@frozeman  , @CJ42 and I  found that the better way to setData in `ERC725Y` is by passing an array of data which can be set in one transaction, that way we can skip the need to to make a contract call each time we want to set singular form of data.  Same applies for getData.

#### setData

Sets array of data at multiple keys. 

```solidity
function setData(bytes32[] calldata _keys, bytes[] calldata _values) public 
```

#### getData

Returns array of data at multiple keys.

```solidity
function getData(bytes32[] calldata _keys) public view returns(bytes[] memory)
```

**Comment by poojaranjan** [comment]
With the recent changes in the process, it is highly recommended to create a discussion thread at Fellowship of Ethereum Magicians instead of "Issue" of this repo and add that FEM link to be updated to the proposal in "Discussions-To" section. 
This helps to have the history of discussion in a single place that could be easily referred to even after the proposal is "Final".

Just FYI - another important change is that a proposal needs to be moved to "Review" status before it can be moved in the "Last Call". So if/when the proposal is ready for review, please be sure to create a pull request for the appropriate status change.

**Comment by Joachim-Lebrun** [comment]
i understand the point of view, but in my opinion, you can still use the standard interfaces of ERC725 and implement a batch function in your implementation contract to call the standard single function several times if needed, in terms of gas cost it is also better to do it this way as you don't want to call the batch function when you do a single add

**Comment by YamenMerhi** [comment]
## Update
Re-adding removed functions as overloaded functions.
More details: https://github.com/ethereum/EIPs/pull/4937
