### ISSUE TITLE
Replace the link to CC0 with a link to the LICENCE file

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5031]
Self-explanatory: replace all occurrences of `https://creativecommons.org/publicdomain/zero/1.0/` with `../LICENCE`, and include LICENCE with the deployment.

**Comment by MicahZoltu** [comment]
I'm going to close this so we can keep the discussion focused in the open PR.  In general, I prefer to either have a PR or an issue for changes so the discussion remains focused.  Since you already have a PR out, that feels like where we should consolidate.  Let me know if you disagree and we can re-open this.
