### ISSUE TITLE
ERC: Pub/Sub + web sockets in web3.js

### ISSUE THREAD

**Issue by frozeman** [ethereum/EIPs#51]
```
ERC: 25
Title: Pub/Sub + web sockets in web3.js
Status: Draft
Type: Informational
Created: 08.01.2016
Resolution: https://github.com/ethereum/web3.js
```
# Abstract

This ERC is to get some opinions on the coming changes in the RPC layer and the web3.js API.
We want to introduce a publication/subscription support for the RPC layer, so that dapps can subscribe for events and get notified when they happened, without that they have to constantly poll for information.

# Motivation

The main motivation for this is to provide a modern push based API for dapps, to reduce the CPU and code overhead for constant polling of data.

Once a dapp crosses a certain size, the amount of information it requires to be notified by the node rises.
Some information, will only happen very rarely and some more often. With the current polling cycle we make come easily up to a batch request with 20-40 request, which we poll every 200ms.   
This creates a CPU overhead in the dapp as well as in the node, in 95% of the cases the requests come back with not change.

So push to the rescue.  
We introduced a [new push API](https://hackpad.com/RPC-interface-VDul0tsDu1t), based on the JSON RPC 2.0 notification support and already implemented that in the geth node's RPC layer.
It works fine with the current IPC socket connection and is implemented in the web3.js#subscriptions branch.

To make it working for the HTTP transport layer we need to introduce web socket support.  

This ERC is mainly to discuss the pros and cons of moving to web sockets. Whether normal HTTP requests should be deprecated or not etc.

# Usage

Web sockets will be introduced like another provider and will work the same as the currently existing IPC provider. Once you choose to use the web socket provider, all communication (method calls, notfications) go through an open web socket created by the provider module.

# Pros and Cons

As much as web sockets improve the development of dapps, it has some certain drawbacks and based on those, we need to decide in which direction to go here.

## Pros

- push notifications, allowing for pub/sub
- faster notification
- less CPU usage on the node (no polling request to process) and on the Dapps (no sending and analysing of poll cycles)

## Cons

- in the current implementation, subscriptions are based on sockets, so lost connections would require the dapp to re-subscribe (or we could try to do this automatically in web3.js)
- web sockets are problematic on mobile devices, due to the cell tower switches and unstable internet connections
   - certain cell towers/mobile providers, can cancel and regain connections without the dapp being notified, therefore loose the subscription without noticing it
   - some mobile providers don't allow web sockets at all. (could be an outdated info)
- Dapps couldn't make synchronous calls anymore, as web sockets don't allow that (which are a no go for UI's anyway).

# Deprecation

Ideally i would like to remove all polling code from web3.js and the nodes RPC side, so that for notifications sockets is the only way. This will clean up the complexity of both web3.js and the node and remove the need to maintain a legacy connection.

We could keep the HTTP request based providers for all simple calls. This would allow to still request, but not use filters etc anymore, as they would require push.

# Community Request

Please give comments and reasons, why we should go in one way or another. Please lets keep this ERC short :)

**Comment by tcoulter** [comment]
I'm very excited about this. One point I'd like to hit home:
> in the current implementation, subscriptions are based on sockets, so lost connections would require the dapp to re-subscribe (or we could try to do this automatically in web3.js)
Web3 should work on reconnecting on its own. I'd love it if Web3 fires events when the connection has dropped or reconnected, and if the dapp wants to it could handle those events and respond accordingly. But I think it should be Web3's responsibility to maintain a connection and not place that burden onto each dapp.

If we reconnected automatically, mobile devices would work more seamlessly as a connection would drop on cell tower change, but would automatically reconnect behind the scenes with no hindrance to the user.

**Comment by bas-vk** [comment]
If we decide to implement the WS interface I would like to see the current HTTP interface marked deprecated and removed in the future. Removing only the polling methods from the current HTTP interface and let the rest intact doesn't make much sense. Any non trivial DApp will probably want to use these filters an thus making the HTTP interface unusable.

Wen a connection is droped and reestablished I would not let web3 try to recreate the subscriptions. What should happen if a connection is recreated after 1 second, or after 1 minute, or after 10 minutes? By default I would simply drop the subscriptions and notify the DApp that the connection is lost. Maybe you can allow DApps to give web3 a callback that is called when the connection is reestablished. That callback can receive the subscriptions that were active when the connection was dropped. DApps can then recreate the subscriptions if necessary.

**Comment by tcoulter** [comment]
@bas-vk See your point. But I think a) most dapps (let's say 9 out of 10) will want to reconnect, and b) information about the status can be handled by events. At the very worst, I think we should make reconnection optional rather than default, because there's no reason for each dapp to write the same reconnection code. 

Some prior art regarding reconnection as an option:

1. Socket.io makes it optional: http://socket.io/docs/client-api/#manager(url:string,-opts:object)
1. In Faye, it's automatic (search "Retry interval" within the page): http://faye.jcoglan.com/browser.html
1. PubNub reconnects automatically, with some "catch up" mechanism that relays missed messages: https://www.pubnub.com/knowledge-base/discussion/332/how-does-auto-reconnect-work

**Comment by frozeman** [comment]
I would also go with automatic reconnect.
Though i would not know how to get missed data..

**Comment by tcoulter** [comment]
@frozeman That probably needs to be up to the dapp. Some dapps care about the most recent state, and so will just refresh. Others will need to backtrack over the blocks that were missed between drop and reconnection. I think with proper events dapps can do the right thing for their context.

**Comment by frozeman** [comment]
I would like to deprecate the `eth_newFilter` and `eth_getFilterMessages` endpoints and remove the polling form web3.js

So that the API works still on normal HTTP requests, just not the polling etc. for this you need to use `eth_subscribe` on a socket connection

**Comment by janx** [comment]
This is cool.

I'd like to keep normal HTTP api, for reason 1. who doesn't like `curl` friendly API :)  and 2. polling is more stable.

**Comment by frozeman** [comment]
We intended to remove the polling.

Though there is an idea to add a polling feature to the current new subscription model, tho this is not fully agreed on, nor implemented.

**Comment by janx** [comment]
By polling I meant something like web3.js normal HTTP api + my own `setInterval`, not that buried in web3.js.

+1 to remove the current polling.

**Comment by tcoulter** [comment]
Note about maintaining our websocket connections within web3:

I strongly recommend we implement a heartbeat mechanism on top of the websocket connection to provide dapps quicker information about the state of their connectivity. You can see a live demo of how websocket responds to connectivity issues in this video, which is to say they respond poorly:

https://youtu.be/3MFlyQshsvY

**I've also detailed the issues below.**

1. In the case of an internet connection disruption, the websocket object doesn't receive a disconnect event until a websocket message has been sent to the server from the browser. 
1. Between the time of the internet disruption and when a message is sent from the browser, all messages pushed from the server are lost.
1. This means there could be minutes or more of non-connectivity without a status update, increasing the amount of backdata that needs to be gathered on reconnection.  
1. Furthermore, there are issues that exacerbate this period of non-connectivity without update:
  1. Even if the internet connection comes back online, the websocket connection still won't be notified of a disruption until a websocket message is sent.
  1. Even worse, if the internet connection stays disconnected, the websocket object won't be notified **at all** of connection interruption (at least, within an acceptable time period) **even if** a websocket message is sent. Both these issues are shown in the video above.
1. This is unacceptable for dapps that rely on an immediate and up-to-date connection to the network (think financial instruments or block explorers), but it's also unacceptable for normal dapps that would like to maintain a good user experience even during periods of disconnectivity.
1. Possibly the most important point: In building our websocket implementation, we have a chance to solve this problem for everyone. 

An easy solution is to maintain a web3-level heartbeat system (think, ping/pong, back and forth between browser and server). The browser (web3) pings the websocket server sending a normal message but containing a specific payload, and the server responds quickly with a pong. After a certain timeout (say, a few seconds, or 10?) we give up on the connection and fire a disconnect message ourselves if we haven't received the pong response. 

There's no reason every dapp developer should have to implement this behavior themselves, and I think better status checking would apply universally. At worst, if people don't want it, we could easily make it configurable. Finally, I don't think we should trust browsers websocket implementations to correctly communicate their connection status, because as proven in the video below they're poor at doing it. I can easily profile other browsers if you prefer.

**Comment by frozeman** [comment]
@tcoulter thanks for your testing skills here ;) I really appreciate that you recorded the video. @bas-vk  As it seems we need to add this heartbeat to the web3.js web socket provider then.

The IPC socket immediately responds, but thats probably due to its nature of using the current filesystem and a local system.

**Comment by SilentCicero** [comment]
@frozeman I agree with @tcoulter a heartbeat mechanism would be really nice to get some assurances. Also I'm completely in favor of dropping polling. The nights I'd spend watching all those calls... :)

**Comment by tcoulter** [comment]
Hey @frozeman - why is this closed? Is it not on the table anymore?

**Comment by MicahZoltu** [comment]
Ping.  Is this pub/sub over web sockets dead in the water?  If so, why?  Geth still has an implementation for it and I believe Parity has plans for one, but both should stop if this is dead for a reason.  If this isn't really dead, where has discussion continued at?

**Comment by tjayrush** [comment]
> We could keep the HTTP request based providers for all simple calls. 

If I understand this discussion correctly, there is a suggestion to remove support for querying the node using something like 'curl.' If that is correct? I think this would remove a significant capability that pub/sub won't meet. (Although, I'm open to being argued out of that position--I don't know enough about pub/sub.)

I write C++ code that 'scans' the chain. This means I start at any block, retrieve the block, then retrieve each transaction in the block, then each of the receipts for each transaction, etc. I do this using 'curl.' It's slow as hell, but I cache the data in a local database which means the next time I try to scan it's significantly faster.

This allows me to do all sorts of data analysis on the chain as a whole (as opposed to say one or a small collection of addresses). Another use for the method is what I call "Forensic Accounting." I'm not sure pub/sub would work. At the very least, it would be made much more difficult.

My code is dependent on the ability to get the block/transaction/receipt data "on-demand." As you develop this EIP, please keep in mind that some code interacts with the data using things other than  Javascript and web3.js.

Thanks.

**Comment by shayanb** [comment]
Bump

**Comment by frozeman** [comment]
This is not dead, and now integral part of web3.js 1.0.0
I would suggest parity to add WS support and Pub/Sub support if they haven't done so yet. See also my comments here: https://github.com/ethereum/web3.js/issues/937

**Comment by frozeman** [comment]
For the sake of supporting HTTP with subscriptions i suggest adding a `eth_pollSubscription` functions for HTTP endpoints (Its not yet in geth either).

The main advantage of have everyone push now under `eth_subscribe: [type, options]` is that we can additional ones, like get storage changes etc, which would improve dapp development a lot.

**Comment by tjayrush** [comment]
There's mention above of depreciating certain portions of the RPC. Has the list of features being depreciated been defined? My concern is to preserve the ability to scan the chain per block/per transaction/per trace from first block to last on demand. Do these changes negatively effect that feature?

**Comment by frozeman** [comment]
You can still scan the blockchain by fetching its blocks, but at some point most nodes wont contain the full history anymore i guess, so this will be only interesting for archive nodes.

**Comment by Shrugs** [comment]
Just to clarify for @tjayrush, this is only intended to deprecate "polling" HTTP connections that currently result in useless computations.

> So that the API works still on normal HTTP requests, just not the polling etc

---

+1 for handling reconnects (and potentially subscription replay, but it might not be a popular "default")
+1 for heartbeats ala webpack-hot-middleware and exposing the connection state in some way (event emitter or callback with status metadata seem reasonable).

How does Meteor tackle this? I'd expect that they have strong experience (and opinions) with websockets and the various connectivity issues/solutions.

**Comment by frozeman** [comment]
There is a way to resubscribe, but this needs to be better tested and probably improved.
For connection errors you have the `end` event on the provider.

**Comment by tjayrush** [comment]
@Shrugs Do you know which RPC interfaces are the 'polling' ones? Are the the 'filter' commands or others? I use eth_getBlock, eth_getTransactionByHash, on Parity (trace_transaction), etc. The ones that get me the raw data.

**Comment by frozeman** [comment]
The poling ones currently are `eth_getFilterMessages` and `shh_getFilterMessages`

**Comment by Shrugs** [comment]
@tjayrush "polling" api calls would give you an asynchronous stream of data. They work by sending normal one-off requests at a regular interval behind the scenes; there's no "polling" RPC interface; it's just a loop in the client library somewhere to make developer's lives easier.

Those API calls you're using are the standard one-and-done requests to get information; removing those would be a little odd, since that sort of information retrieval is the entire reason client libraries like this exist. You're not in any danger of having to rewrite your code.

So yes, the filter commands, like frozeman mentioned earlier:
> I would like to deprecate the eth_newFilter and eth_getFilterMessages endpoints and remove the polling form web3.js

**Comment by frozeman** [comment]
The reasons to move to `eth_subscribe` is to allow for more push based subscriptions, like state changes etc in the future, the filter polling works only for that: filters for logs.

We could use long polling when we add a `eth_pollSubscription`, and i am actually in favour of that, but it is not up to me to implement that.
