### ISSUE TITLE
Proposals to close EIP Discussion Issues

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIPs#5127]
In the EIPIP meeting 57, the group briefly discussed options for closing EIP discussions open Issues.
Please respond with your recommendation to design a bot or take manual actions accordingly.

1.  Bot closes all "discussion-to" Issues with a remark, continue discussion on "Fellowship of Ethereum Magicians" and author may migrate discussion.
2. Bot closes any Issue inactive for 6 months, irrespective of it being a "discussion-to" link 
3. Admin closes "discussion-to" Issues  for proposals in `Final`, `Stagnant`, `Withdrawn` status

**Comment by Pandapip1** [comment]
I'll keep track of the relevant issues here.

Isn't a discussion-to link (just a proposal):
- #637
- #864
- #958
- #1190
- #1238
- #1257
- #1411
- #1553
- #1631
- #1888
- #2350
- #4469

Final EIPs:
- #225 (EIP-225)
- #2319 (EIP-1193)
- #2907 (EIP-2981)
- #3608 (EIP-3607)

Withdrawn EIPs :
- None

Stagnant EIPs:
- #1523 (EIP-1523)
- #1902 (EIP-1901)
- #2337 (EIP-2333)
- #3042 (EIP-3000)
- #3132 (EIP-3135)
- #3384 (EIP-3386)
- #3590 (EIP-3589)

Last Call:
- #2365 (EIP-2364, Deadline 2021-11-19)
- #2465 (EIP-2464, Deadline 2021-11-19)
- #2535 (EIP-2535, Deadline 2020-08-15)

Draft EIPs:
- #2439 (EIP-
- #3225 (EIP-
- #3641 (EIP-
- #3772 (EIP-
- #3753 (EIP-
- #3782 (EIP-
- #4431 (EIP-

Review EIPs:
- #2613 (EIP-
- #2983 (EIP-

**Comment by Pandapip1** [comment]
I am weakly in favor of no. 1. I think that attaching a link to the (closed) GitHub issue is sufficient to continue the discussion. I propose that to avoid EIP editor work, it should be the responsibility of the EIP authors to migrate the links. However, I can see how this might be inconvenient, so if it could be determined that the inconvenience of migrating the discussion link is greater than the inconvenience/confusion caused by the presence of the issues,

I am weakly in favor of no. 2, as the discussions-to links aren't even up to date. Most discussion-to links aren't marked as such (and #4431 is marked as discussions-to _despite_ the real discussions-to link being migrated to Ethereum magicians). However, I am weakly against the stale bot in general. I feel that every issue should be manually determined to be stale (and if the number of issues moves down to one page when no. 3 is implemented, this is very feasible).  

I am strongly in favor of no. 3. Closing Final and Withdrawn EIPs is a no-brainer; they aren't going to be changed, so there's no discussion to be had. All discussion should be for a _new_ EIP that fixes/improves the older one. Stagnant EIPs should also be closed, as the links can always be re-opened if/when said EIP moves out of stagnant.

**Comment by MicahZoltu** [comment]
I suspect that (3) will likely be the least contentious and so I suggest we focus on that in the short term.

Migrating from GitHub to Ethereum Magicians is unlikely to go smoothly.  Some discussions-to links have a lot of discussion, and just copy/pasting that into the body of a single message will make it much harder to read and link compared to current discussions.  The common case is that an issue receives a lot of discussion while it is actively being edited, but that eventually dies out.  I think if we simply close those issues (via (2) or (3)) the negative effects of this problem will go away and we won't have to do a bunch of work.

**Comment by mryalamanchi** [comment]
In strong favour of 3., writing bot and solving for that is just extra work and it can be rather quickly done manually!

Since @Pandapip1 has already created a list to start with, we can focus on that and find the rest async and keep updating the list here in the comments itself.

Wdyt?

**Comment by MicahZoltu** [comment]
I would like to get additional feedback from other editors before moving forward with 3, but so far it does seem like the popular choice.

**Comment by gcolvin** [comment]
3 is fine by me.  The author can re-open if need be.

**Comment by SamWilsn** [comment]
3 is also fine with me.

**Comment by MicahZoltu** [comment]
I have closed the discussions-to for the Stagnant and Final EIPs listed by @Pandapip1.

**Comment by Pandapip1** [comment]
While you're at it, you should close all the issues in the first list, as they aren't discussion-to links.

**Comment by Pandapip1** [comment]
I would also like to add another option:

4. All discussion-to issues are manually closed, but the discussion may continue. The EIP authors should create threads on Ethereum magicians, directing users to use the closed GitHub issue.

**Comment by MicahZoltu** [comment]
> While you're at it, you should close all the issues in the first list, as they aren't discussion-to links.

Done.

**Comment by lightclient** [comment]
I'm good with 2) and 3).

**Comment by gcolvin** [comment]
I think the consensus is 3?

**Comment by MicahZoltu** [comment]
I believe we have completed (3) at this point.  There will be stragglers over time as grandfathered EIPs enter final/stagnant/withdrawn but there should be relatively few at this point.  Do you feel this issue is resolved enough to warrant closing it @Pandapip1?

**Comment by Pandapip1** [comment]
Sure.

**Comment by poojaranjan** [comment]
Closing as per rough consensus in favor of option 3.
