### ISSUE TITLE
Disallow the word "Smart" in the titles (and descriptions) of EIPs

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIPs#5308]
Like #5009 but with the word "smart" instead.

**Comment by SamWilsn** [comment]
I can't thumb up this enough.

**Comment by Pandapip1** [comment]
> maybe we should allow smart, but only as part of "smart contract"?

I think that it's unambiguous enough to just use "contract." If you're talking about any (proto-)EIP other than https://github.com/ethereum/EIPs/pull/5289, there's only one possible interpretation.

**Comment by xinbenlv** [comment]
I object to this editorial rule. I think it shall be author to decide the name. I don't think editor group already have or shall have the power to make such judgement.

**Comment by MicahZoltu** [comment]
> As much as I appreciate the intention to make description more readable, I object to this editorial rule. I think it shall be author to decide the name. I don't think editor group already have or shall have the power to make such judgement.

I believe the problem here is that 99% of ERCs are just contract interface definitions, and people have a tendency to not realize the amount of redundancy they are including in their title when they say "X Smart Contract Standard".  The entire latter portion of that sentence is almost entirely redundant and if we say nothing we can end up in a situation where every single ERC is named following that pattern or a very similar one.

As editors, we have a better overall grasp of the EIP ecosystem and recognize the redundancy where drive-by authors may not.

FWIW: The text added for discouraging the word "Standard" in titles wasn't a hard requirement, it was just a **SHOULD NOT** so there is leeway for exceptions.  In the vast, vast, majority of cases in my experience though, the authors are just unwittingly using "standard" and "smart" redundantly.
