### ISSUE TITLE
ERC: add decimal fixed point support to ABI

### ISSUE THREAD

**Issue by vbuterin** [ethereum/EIPs#598]
### Summary

Extend the ABI standard to include support for decimal fixed point values.

### Motivation

Decimal fixed point values are used in Viper and may be used in other HLLs on ethereum in the future. Unlike traditional binary fixed point and decimal fixed point, decimal fixed point has a "what you see is what you get" property in that any value that can be written in decimal, and any sum and difference (and to a limited extent product) of such values, can be stored as a decimal fixed point value precisely without any rounding, whereas in a binary representation values such as 0.3 need to get rounded. For this reason, decimal fixed point values are already recommended for use in many financial applications.

### Specification

Add to the ABI standard the variable type `decimal<n>` (eg. `decimal3`, `decimal10`), where `n` specifies the number of decimal places. A value `x` is encoded as `left_zpad32(int_to_big_endian(x * 10**n) % 2**256)` (the modulus ensures that negative numbers can also be encoded).

Decoding is in two steps:

1. Check whether the first byte is greater than or equal to 0x80 (ie. the value is negative)
2. If the first byte is >= 0x80, then decode the decimal value via `(big_endian_to_int(bytes) - 2**256) / 10**n`. Otherwise, use `big_endian_to_int(bytes) / 10**n`.

**Comment by bobsummerwill** [comment]
+ @VoR0220, who has been working on fixed-point support in Solidity for months, and likely has useful feedback.

**Comment by VoR0220** [comment]
Nothing to add too much, this is exactly what has been decided along with @chriseth . It should be noted that this is in fact a decimal as opposed to a traditional fixed point number. Therefore the decimal<n> is not truly sufficient, but rather the decimal<n>x<m>with <n> to denote size of the number overall and <m> to denote the number of decimal places. Otherwise, this can be merged.

**Comment by vbuterin** [comment]
Got it. Sounds good to me.

**Comment by michaelsproul** [comment]
What's the status of this? I've been playing around with Viper and have noticed that `pyethereum` is the only client with support for a `decimal` ABI (since commit https://github.com/ethereum/pyethereum/commit/237df71d1eafeafaafd6bca16d0ba066f3d1fff3).

Elsewhere, there is discussion of using the `fixed` types to implement Viper's `decimal` (here: https://github.com/ethereum/vyper/issues/566).

I would really like to be able to (easily) use `decimal` values in Populus, but I don't want to hack the "wrong" approach into `web3.py` (upon which Populus depends).
