### ISSUE TITLE
Let deployer destroy a blank contract and get fund back

### ISSUE THREAD

**Issue by pynixwang** [ethereum/EIPs#709]
I write a script to do some transaction, but some hash key error cause transaction to is `null`,then, it create a blank contract and transfer my ether into it, then I google for some information, other people also make this mistake, such as 999ether.
is a blank contract meaningless, let deployer destroy it?

**Comment by pynixwang** [comment]
[reddit 1000ether](https://np.reddit.com/r/Buttcoin/comments/3l6ezi/sfyl_etherbutter_sends_1000_in_eth_tokens_to_an/?st=j791lemo&sh=1465ad8c)

**Comment by pynixwang** [comment]
[contract address](https://etherscan.io/address/0xae7a1b1ba864696bcdcec94a34fb5836ca9a3910)

**Comment by djrtwo** [comment]
I wouldn't think adding destroying a good way to go. People might have used blank contracts as a proof of burn. The question is should there be a feature to make a "blank contract" at all. If this is a common mistake and has no use case, I could see an argument for future transactions failing instead of creating an empty contract.

**Comment by nicksavers** [comment]
@pynixwang Your case seems to be covered by https://github.com/ethereum/EIPs/issues/156. If that EIP is sufficient for you, could you continue your comments there and close this issue?

**Comment by pynixwang** [comment]
@nicksavers OK
