### ISSUE TITLE
Serenity Validators, As Official Decentralized Casper Staking Pool Smart Contracts

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/EIPs#73]
I'm a total novice at cryptocurrency tech, but was thinking it might be feasible to have each Serenity validator instead of being X number of randomly chosen accounts that meet certain criteria, be X number official Casper decentralized staking pool smart contracts instead? Wouldn't this simultaneously solve these two potential issues:

1) _Everybody_ can participate in staking _at any time_, _with any amount of ETH_.

2) With _multiple_ official decentralized staking pools to choose from _that are all identical protocols_, pool centralization issues cannot easily occur.

Sorry if I'm missing something here from a technical perspective, I'm just a web2 guy for now (slowly getting there with web3).

**Comment by Smithgift** [comment]
Here's a technical bugaboo: CASPER validators must have static validating code so that bets are verifiable on an absolute level. Because of this, a pool's multisig (assuming that's the most likely way to work these things) must remain constant from the moment of its creation. Because of *that*, there's no way for members to easily enter or leave, without completely rebuilding the pool.

**Comment by taoteh1221** [comment]
Maybe there is a workaround for this, via loading up a staking pool smart contract with participants _before it goes live_, then locking it down so it's ready to enter a validator cycle. Then have the _existing live pools expire_ / release deposits and earnings after a certain period of time, and the new ready and waiting pool takes it's place...having no more than 1 pool _fully loaded up and locked in_ waiting to go live, and 1 additional pool _actively still loading up_ with participants (and locking in when the other pool goes live as a validator).
