### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by ProphetZX** [ethereum/EIPs#7498]
@abcoathup and @Pandapip1:

Hi there,

I recently noticed that VALUABLE and IMPORTANT contributions are regularly discredited as spam. I personally clearly reject such behaviour, so please provide a reason why you think that such a contribution should be marked as spam and do not simply close such threads.

Thank you and regards

ProphetXZ

              SPAM

_Originally posted by @abcoathup in https://github.com/ethereum/EIPs/issues/7491#issuecomment-1681447863_

**Comment by abcoathup** [comment]
I commented SPAM because it was an issue created with content not related to EIP repo: https://github.com/ethereum/EIPs/issues/7491#issuecomment-1681447863

I see a fair few SPAM issues being created, so comment as such when they occur.  On topic issues/PRs are welcome.

**Comment by Pandapip1** [comment]
> please provide a reason why you think that such a contribution should be marked as spam

The issue contained no information or actionable items. Those issues will be presumed to be spam and closed as such, but generally no actions are taken against accounts. If you feel that you opened an actual issue and it was closed as spam, please open a new issue referencing the old one and provide a nonzero amount of information.

> do not simply close such threads

I will continue to close threads that contain no information and follow common spam patterns.

I will be closing this issue, as I feel that it is resolved. If you feel otherwise, please tell me and I (or someone else) will reopen it.
