### ISSUE TITLE
Extend EIP1 with an option for "EIP editor"

### ISSUE THREAD

**Issue by axic** [ethereum/EIPs#797]
There are a lot of specifications which could be published as an EIP/ERC, which have been around and (un)maintained in random places. Some of these include: ABI specification, NatSpec, secure private key storage in clients, RPC methods, etc.

Since these have been specification efforts by many parties, it may look weird if someone creates an EIP with a single author and collecting all the authors may seem impractical. 

I propose to introduce an option that instead of a list of authors the EIP/ERC to contain only an `Editor` field listing the person(s) who created the EIP based on an original reference, which should be stated in the `References` section.

I hope this would encourage people in the space, who might have not thought about this option given the issue with claiming authorship.

**Comment by pirapira** [comment]
Some people don't care and file EIPs that mainly refer to resources on the Internet (e.g. https://github.com/ethereum/EIPs/pull/779/files) as an author.

If an EIP is not filed by the author, I cannot trust the CC0 notice so I cannot merge it.

**Comment by axic** [comment]
To clarify, the idea is here that the person is still the author of the text, but not necessarily the ideas represented in it (e.g. formalising the ABI spec as an EIP).

**Comment by axic** [comment]
cc @Souptacular @MicahZoltu @lightclient for some comments.

**Comment by lightclient** [comment]
I like the idea a lot. I agree that there are a lot of great EIP-able ideas / works (especially in terms of informational EIPs). Using "editor" may overload its meaning in the context of the EIPs repo. If someone is writing the EIP from scratch, just using the ideas (which are not copyrightable) that are based on the other author, is there a concern with including both people in the author line and reference the original work somewhere in the EIP?

Semi-related: Is it asking too much to remove the CC0 notice and allow the author to retain their copyright? We could have them license the use of it via something similar to [RFC-5378](https://tools.ietf.org/html/rfc5378). This would probably make the above process easier since the EIP wouldn't need to be written from scratch.

**Comment by MicahZoltu** [comment]
> Is it asking too much to remove the CC0 notice and allow the author to retain their copyright?

Short answer is yes.  😄 This has been *heavily* debated in the past and there are some people who are staunchly against removing the CC0 requirement.  We could certainly discuss it again, though I suspect most of the people are kind of tired of debating it at this point.

@axic Why not just rename the `Author` field to `Editor` or `Maintainer`?  Since EIPs are all CC0, the "author" really doesn't matter (since CC0 doesn't require attribution), and I feel like editor or maintainer would more correctly capture the role the person is playing in the EIP process.

**Comment by MicahZoltu** [comment]
Thinking more on this, I don't like `Editor` because I think that is likely to get confused with EIP Editors (e.g., you and I).  I like `Maintainer` since I think that most accurately reflects what that field represents.
