### ISSUE TITLE
EIP 838: ABI specification for REVERT reason string

### ISSUE THREAD

**Issue by federicobond** [ethereum/EIPs#838]
EIP: 838
    Title: ABI specification for REVERT reason string
    Author: Federico Bond
    Status: Draft
    Created: 2017-01-20

## Simple Summary

A proposal to extend the ABI specification to include typed errors in the REVERT reason string.

## Abstract

This proposal specifies how to encode potential error conditions in the JSON ABI of a smart contract. A high-level language could then provide a syntax for declaring and throwing these errors. The compiler will encode these errors in the `reason` parameter of the `REVERT` opcode in a way that can be easily reconstructed by libraries such as web3.

## Motivation

It's important to provide clear feedback to users (and developers) about what went wrong with their Ethereum transactions. The `REVERT` opcode is a step in the right direction, as it allows smart contract developers to encode a message describing the failure in the reason parameter. There is an [implementation](1) under review in Solidity that accepts a string, thus providing a low-level interface to this parameter. However, standardizing a method for passing errors from this parameter back to clients will bring many benefits to both users and developers.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.

## Specification

To conform to this specification, compilers producing JSON ABIs SHOULD include error declarations alongside functions and events. Each error object MUST contain the keys `name` (string) and `arguments` (same types as the function’s `inputs` list). The value of `type` MUST be "error".

Example:
```
{ "type": "error", "name": "InsufficientBalance", "arguments": [ { "name": "amount", "type": "uint256" } ] }
```

A selector for this error can be computed from its signature (`InsufficientBalance()` for the example above) in the same way that it's currently done for public functions and events. This selector MUST be included in the reason string so that clients can perform a lookup. Any arguments for the error are [RLP](https://github.com/ethereum/wiki/wiki/RLP) encoded in the same way as return values from functions. The exact format in which both the selector and the arguments are encoded is to be defined. The Solidity implementation mentioned above leaves room for expansion by prefixing the free-form string with `uint256(0)`.

A high-level language like Solidity can then implement a syntax like this:

```
contract MyToken {
  error InsufficientFunds(uint256 amount);

  function transfer(address _to, uint256 _amount) {
    if (balances[msg.sender] <= _amount)
       throw InsufficientFunds(_amount);
    ...
  }
  ...
}
```

## Possible extensions

1. A [NatSpec](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) comment above the error declaration can be used to provide a default error message. Arguments to the error can be interpolated in the message string with familiar NatSpec syntax.

```
/// @notice You don't have enough funds to transfer `amount`.
error InsufficientFunds(uint256 amount);
```

2. A function may declare to its callers which errors it can throw. A list of these errors must be included in the JSON ABI item for that function, under the `errors` key. Example:

```
function transfer(address _to, uint256 _amount) throws(InsufficientFunds);
```

Special consideration should be given to error overloading if we want to support a similar syntax in the future, as errors with same name but different arguments will produce a different selector.

## Backwards Compatibility

Apps and tools that have not implemented this spec can ignore the encoded reason string when it's not prefixed by zero.

## Revisions

 * 2018/01/23: Improved writing and clarified summary
 * 2018/01/10: Initial draft

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

[1]: https://github.com/ethereum/solidity/pull/3364

**Comment by sinzin91** [comment]
Great idea!

**Comment by pirapira** [comment]
Pinging @axic: he had some ideas how to use `REVERT` when he proposed `REVERT`.

**Comment by VoR0220** [comment]
This is an excellent idea and is the perfect workaround to the problem with reverting on the chain while containing the exact errors. It makes it interpretive like event logs. I like it.

**Comment by Arachnid** [comment]
Good idea. The term "reason string" is misleading, though - it's not a string, just return data.

**Comment by federicobond** [comment]
You are right. I took `string` from the type of the parameter in the Solidity implementation.

**Comment by axic** [comment]
We have discussed how this could be implemented and I think we are going on a path to have this in the future.

The current revert-with-reason proposal had a payload of `<version><ABI encoded string>`, which resulted in `00..00 00..20 <len> <data>`.

Now we could instead just assume that there is a generic error with a signature of `Error<string>`, which hashes to `2939df17` followed by an ABI encoded string, therefore `revert("oh noes")` would result in the data `2939df17 00...20 00..07 6f68206e6f6573..00`.

We could also have `Error(cstring)`, where `cstring` is encoded as `bytes32` in the ABI, but is assumed to be a C-string, where a zero denotes the end of the string. In that case for short messages we could save same space: `bb6ffe56 6f68206e6f6573..00`

**Comment by Arachnid** [comment]
Why not just allow functions to specify an error ABI just as they currently specify a return ABI?

**Comment by axic** [comment]
> Why not just allow functions to specify an error ABI just as they currently specify a return ABI?

Hopefully that will be possible in the future, but right now we only have a feature which supports passing an error string via `require()` and `revert()`. This way people can get started with a generic error reporting feature and if in the future we extend this to support something similar to what this EIP is proposing then it will be properly part of the ABI.

**Comment by Arachnid** [comment]
In that case, why not just return an ABI encoded string, and say that all functions implicitly have an error ABI of `string`? The function selector seems unnecessary here; we don't have 'return selectors'.

**Comment by Arachnid** [comment]
I'm suggesting that having an error selector in general is needless.

**Comment by axic** [comment]
Why do you think it is needless?

I imagine that most errors can be encoded as a selector only, if it is exposed to the user, without any other ABI payload.

For example:
```
contract Wallet {
  error UnauthorisedUser();
  error InsufficientBalance();

  function authorise(bytes32 hash) {
    require(authorisedUsers[msg.sender], UnauthorisedUser); // encoded as a selector only
    require(msg.balance >= pending[hash].amount, InsufficientBalance); // encoded as a selector only
    revert("Unimplemented feature"); // encoded as Error(string) + string
  }
}
```

**Comment by Arachnid** [comment]
I guess the question is whether we're implementing an exception mechanism, where uncaught exceptions propagate automatically to the caller, or whether it's a C- or Go-style error mechanism. If the latter, it seems to me that errors and return values should be encoded the same way, with an ABI; if you want to distinguish error types, you can return an enum.

**Comment by chriseth** [comment]
@Arachnid my impression of this is the former, this is also the default implementation of function calls, errors are always propagated upwards. Otherwise you have to implement a handler for every single error type and this includes all EVM errors like stack overflow.

So since errors are propagated, we cannot use a fixed enum and thus use the function selector to distinguish the actual error types.

I thought about using a function selector and basically forcing the name to be empty, but dropped it in the end because this would allow you to decode the data in more cases (you can guess most type combinations), but that still does not help you: Now you know the structure of the data, but you cannot handle it unless you also know the meaning. The meaning is provided by having an error type or name. This is of course still no silver bullet, but I think this is as far as we can go when we want to support both propagation of arbitrary errors and handling of some known errors.

**Comment by Arachnid** [comment]
Okay; if the idea is that errors can be nonlocal and propagate to arbitrary callers, I can see how sending an identifier along with everything else makes sense.

**Comment by jacqueswww** [comment]
Hey there!
Just wanted to get clarity on what was decided in terms of this EIP, so I know what to do for vyper when I want to implement the same. Will the clients support decoding an error message from the ABI definitions? Which clients currently support this?
Basically following <sig: 4 bytes><abi_arguments:x bytes> format?

**Comment by axic** [comment]
@jacqueswww for the current behaviour see: https://github.com/ethereum/EIPs/issues/838#issuecomment-379238333

I'm writing up a proper description of this.

**Comment by ricmoo** [comment]
I have added this to the experimental TypeScript branch for [ethers.js](https://github.com/ethers-io/ethers.js) and currently I do not see any version byte.

I might suggest the following, if the length (in decoded bytes) of the result is congruent to 4 mod 32, then it is the above <sig><standard abi>. 0 mod 32 indicates nothing special and that the abi should be parsed as usual. Version and additions in the future will change the remainder, but libraries can start inferring from the non-word sized-ness that the result is special, and fail with a generic error if they don’t understand how to interpret the specialness and if they do understand it, do the library specific thing.

**Comment by fulldecent** [comment]
Please explain the caveat "when it's not prefixed by zero" in the backwards compatibility section.

I am concerned what is the cost in practice of this EIP against deployed contract size. The contract size limit is at https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md

Here is a contract I am familiar with https://github.com/0xcert/ethereum-erc721/blob/master/contracts/tokens/NFToken.sol and there are 19 `require` statements and 6 or so require statements. What is the additional cost, in contract size, if each `require` did also include a descriptive statement with RLP-encoded reason arguments when appropriate?

**Comment by federicobond** [comment]
Note that we are already moving towards having rich error reporting in contracts. This EIPs is intended to avoid the wastefulness of storing full strings like “The amount needs to be positive” instead of short 4-byte error selectors with optional arguments.

I haven’t made any calculations on the increased storage requirements, I believe those belong in the discussion of REVERT itself.

**Comment by fulldecent** [comment]
Actually, even the 4-byte selectors are unnecessary. I could explain how that works but it might be a premature optimization. That's why I'm asking for some metrics.

**Comment by ricmoo** [comment]
Keep in mind one advantage of the 4 byte selector is determi omg error conditions vs correct operation. All results from a contract are currently congruent to 0 mod 32 bytes. The 4 bytes extra provides a nice safe way to detect something isn’t normal. Just something to keep in mind. :)

**Comment by LogvinovLeon** [comment]
## Current situation

This EIP was created on 20.01.2018 and last edited on 23.01.2018. Solidity since released [revert reasons](https://github.com/ethereum/solidity/pull/3364) in `v0.4.22` on the 17.04.2018 and people love them. Currently, the assumption is that every error has the implicit ABI `Error(string)`. And it's parameters gets encoded in the same way as function call arguments using ABI encoding.
Therefore:

```solidity
revert("Not enough Ether provided.");
```

Gets encoded as:

```
0x08c379a0                                                         // Function selector for Error(string)
0x0000000000000000000000000000000000000000000000000000000000000020 // Data offset
0x000000000000000000000000000000000000000000000000000000000000001a // String length
0x4e6f7420656e6f7567682045746865722070726f76696465642e000000000000 // String data
```

## Motivation

Sometimes that is not enough and people want to include additional data in their on-chain error messages. This is overall consistent with the idea of:

> moving towards having rich error reporting in contracts @federicobond

It's worth mentioning that as @chriseth wrote above this EIP is not intended to be a solution for go-style error handling. It's not a solution for a happy path. Therefore gas costs should not be of the highest priority here. User experience should be.

Because we're not talking about error-handling in the scope of the transaction (not separate functions) - it doesn't make sense, in my opinion, to define which errors does the function throw. In any real-life scenario, your function will be interacting with other functions so this list of errors will either become really long or if we introduce the hierarchy as in Java - every function will have the topmost error like `IOError` which is of no use.

On the contrary - errors are being thrown by the contracts and they're the one that should be exposing data about their error formats (ABIs).

## Proposed solution

Each solidity contract MAY define additional errors.
```solidity
error UnauthorisedUser(uint userId);
error InsufficientBalance(uint userId, address token);
```
The error schema that is used now MAY be explicitly defined:
```solidity
error Error(string message);
```
but it doesn't need to be. Similar to default constructor.
The ABI is described in the EIP itself. When a revert happens it's parameters are being ABI encoded as if it was the call data using the error ABI.

A high-level language like Solidity can then implement a syntax like this:
```solidity
revert UnauthorisedUser(userId);
revert InsufficientBalance(userId, token);
revert Error("Usual revert reason"); // Results in the same behaviour as `revert("Usual revert reason");`
```
It can be also used in `require` calls
```solidity
require(isAuthorised[userId], UnauthorisedUser(userId));
require(balance[userId][token] > 0, InsufficientBalance(userId, token));
```
And `revert`s
```solidity
revert(UnauthorisedUser(userId));
revert(InsufficientBalance(userId, token));
```

This is fully backwards compatible. Old smart contracts can just update to the new version of Solidity and the code will work.

Moreover - if you don't need additional data and just want error codes - you can define errors without parameters and the revert reason will just be the 4-byte selector.

Client-side libraries can decode those errors and their parameters with human-readable names if they have the ABI of the contract that initiated an error.

**Comment by fulldecent** [comment]
@LogvinovLeon You've done a great job explaining the perspective of the implementing contract and specifying the language.

# Point 1 -- do we actually need data?

Could we also consider a few end-to-end use cases? Examples like 

* `throw InsufficientFunds(_amount);`
* `require(isAuthorised[userId], UnauthorisedUser(userId));`
* `require(balance[userId][token] > 0, InsufficientBalance(userId, token));`

don't look like any revert messages I've seen. Here are two contracts with revert messages we could consider:

* https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-erc20-contracts/src/contracts/token.sol (Java style, without hierarchy)
* https://github.com/compound-finance/compound-money-market/blob/master/contracts/StableCoinInterestRateModel.sol (Golang style)

In both cases they are not passing back data.

I think the above examples when implemented in code are much more likely to be:

* `throw InsufficientFunds();` // Who cares what the amount is? The caller should know what value they entered!
* `require(isAuthorised[userId], CallerNotAuthorized());` // I think the caller should know who they are, no need to tell them.
* `require(balance[userId][token] > 0, InsufficientBalance());` // If this is an ERC-20 style product then I think the user knows who they are and what they are transferring. To return that information would be redundant.

# Topic 2 -- try catch

If `revert` will send data in the same style of ABI as a `call` then we can expect developers will demand this syntax as well:

```solidity
interface ERC20 {
    error InsufficientBalance();
    ...
}

contract Faucet {
    error FaucetEmpty();

    ERC20 underlyingAsset;
 
    function getAirDrop() external {
        try {
            token.transferFrom(address(self), msg.sender, 1)
        } catch(InsufficientBalance /* theError */) {
            throw FaucetEmpty();
        }
    }
}
```

If we are designing specifically with the goal of never having try catch then would should have a full argument on that presented in the EIP.

Practically, there is also a namespacing issue here. Is an `ERC20.InsufficientBalance` equivalent to an error with the same name from a different interface/contract?

# Point 3 -- error propagation

Take for example he air drop contract. What if the underlying asset is an [0xcert implementation of ERC-20](https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-erc20-contracts/src/contracts/token.sol), it also has the error condition `ALLOWANCE_ALREADY_SET`. It is a non-standard extension to ERC-20. This is an error that the caller will not expect. So will this propagate up to the human caller when it fails through the try/catch? The human will see an error like `ERROR: 4d24af38` in MetaMask because it could not be in the contract's ABI.

**Comment by fulldecent** [comment]
I hear the pain. It makes sense. Maybe the simple, and extensible way to do this is:

A normal asset transfer. Already backwards compatible with EIPs like ERC-721.

```solidity
function transfer(address _to, uint256 _amount) throws(byte statusCode);
```

This is how Compound Finance and others already work.

```solidity
function getOraclePrice(address asset, uint256 time) returns(uint256 price) throws(byte statusCode);
```

Here is how your batch transfer would work.

```solidity
function batchTransfer(address asset[], uint256 quantities[], address recipient) 
    returns(uint256 timestamp) 
    throws(byte statusCode, uint256 failedTransferIndex);
```

And all of these support the obvious try-catch syntax:

```solidity
contract BankAgent {
    function settleFunds() {
        uint timestamp;
        try {
            timestamp = batchTransfer(...);
        } catch (uint256 failedTransferIndex) {
            pauseContract(); // block further actions until settlement is possible
        }
    }
}
```

Here the try-catch only supports a single statement. The verbosity is justified by having an explicit code path for when a function call reverts. It is already much cleaner than using assembly.

Then the scope of this EIP is limited a programming convention. To assign semantics to these status codes we need something else like #1066.

---

If semantics (i.e. what exact message does MetaMask and other client software show end users) is important then we need to address the namespacing issue. And we should have buy-in from MetaMask. In contrast, the proposal in this comment is actionable without relying on anybody else.

**Comment by chriseth** [comment]
This has been implemented in Solidity 0.8.4.

**Comment by ricmoo** [comment]
Can we get this added to the official EIPs repository? I'm not sure what it means if the initial draft is final. :)

**Comment by chriseth** [comment]
Oh by the way: Solidity reserved the following selectors for future use:
 - 0x00000000
 - 0xffffffff

And those two currently cannot be defined in user code (which is maybe less relevant for the EIP):
 - `Error(string)`
 - `Panic(uint256)`

So maybe at least the first two could be added to the EIP.

**Comment by chriseth** [comment]
Note that the way Solidity implemented EIP838 could be interpreted to deviate from the standard specified here. Specifically:

> Any arguments for the error are RLP encoded in the same way as return values from functions. The exact format in which both the selector and the arguments are encoded is to be defined. The Solidity implementation mentioned above leaves room for expansion by prefixing the free-form string with uint256(0).

EIP 838 does not specify how data is encoded but suggests RLP. At the same time, it says "in the same way as return values from functions" - which is the case for the Solidity implementation: It uses ABI encoding. More details can be found in the [Solidity documentation](https://docs.soliditylang.org/en/v0.8.4/abi-spec.html#errors)

**Comment by RenanSouza2** [comment]
Hello @federicobond and everyone, Is there any PR with this EIP to officialize it? I think it is import since solidity adopted it.

I also posted this EIP in https://ethereum-magicians.org/t/eip-838-what-is-the-current-status/14671
