### ISSUE TITLE
A simple solution (NO FORK) and blow bitmains rigs off the system

### ISSUE THREAD

**Issue by ghost** [ethereum/EIPs#996]
Increase the dag past 4 gigs when the e3's are released. :)

**Comment by flygoing** [comment]
To manually increase the size of the dag would require a hard fork. This would also invalidate a bunch of gpus currently mining before they we're expected to be too small. I also haven't heard anything about the ASICs being limited to 4gb dag size, is there a source for that?

**Comment by tekcomm** [comment]
It would not require a hard fork and the gpu's that it will effect will be forced anyways in the near future. Bitmain wants a hard fork. Then they will own eth. Sources are like assholes everyone has one the trick is just to get them really drunk.

**Comment by tekcomm** [comment]
Btw, every device bitmain manufactures the coders are from china telcom and all there systems are little Endian. 32 bit  xilinx toolchains.

**Comment by flygoing** [comment]
> It would not require a hard fork
How could you change the dag size without hard forking? The dag is generated based on the current epoch number. You'd either have to change the algorithm that generates the dag, or artificially push the epoch number forward, both of which would cause a hard fork.

>  gpu's that it will effect will be forced anyways in the near future

The DAG, at its current rate, will be below 4 GB until February of 2021. That's 3 years. In my opinion, not considered the near future.

**Comment by Arachnid** [comment]
This can't be done without a hard fork. And there's no particular reason to assume that 4GB is the magic number here.

**Comment by tekcomm** [comment]
Nate, Push the dag forward and invalidating the blocks between would not
cause a hard fork. March 2012, the ancient past Bitocoin Disallowed
transactions with the same TXID, unless the older one was fully spent.
In September
2012
<https://github.com/bitcoin/bitcoin/commit/ab91bf39b7c11e9c86bb2043c24f0f377f1cf514>,
the rule was applied to all blocks, apart from 91,842 and 91,880, which
violate the rule.

What I am proposing is either
A. A simple soft-fork with limited disruption. I already gave you the specs
and why and how it will work.
B. Let eth become bitmains bitch. (Which its not really bitmain its china
telcom and the entire eth system will end up with systems that a single
entity that can remote control them)
C. Change it into a tripple hash with a splash of a hash and hard fork like
monero Pow7.

So there are your three choices.

**Comment by tekcomm** [comment]
Nick 4 gigs is the magic number would you care to make a bet :). I know I
have been a Ti dev for 38 years. I also cracked the ebang miners in one day
and removed there backdoors. The systems are all little endian.  For the
record the magic number is:
:)
34359738368


F:)

**Comment by Eliovp** [comment]
The low activity here concerns me..

There are so many valid points here, good idea's.

It seems to me that certain people seem to be a fan of centralisation or scared to step up.

**Comment by Arachnid** [comment]
As already pointed out several times, this cannot be achieved without a hard fork, as the DAG size is directly determined by the block number.

**Comment by danielyapbc** [comment]
Just fork the damn network already...Bitmain is probably running warehouses with their ETH ASICs..I can't believe how ignorant the ETH Devs can be!

**Comment by tekcomm** [comment]
Daniel,

I already knew that. They have been doing that and they will keep on doing.
I don't think they will be fucking with monero anymore though at least :)

**Comment by tekcomm** [comment]
I just hope they grow a set of balls, and do whats best for the community
and not the Chinese Communist Party. Who it seems the Eth devs put first.

**Comment by tekcomm** [comment]
China Telcom AKA Bitmain, will be in control shortly and I am sure they
will not put any backdoors in there miners to slow them and steal blocks or
to just turn them off remotely. Oh wait they already did that on every
other device. You can read the mea culpa in there own forum on antpool
which they had to shutdown after they admitted to it from the flame war.

**Comment by tekcomm** [comment]
Now that we are completely off topic, At least the devs know that they
could and how to by burning part of the dag. What they do knowing the the
fact that there system is based on a 32 bit kernel and can not deal with a
simple solution. The choice is theres.

**Comment by tekcomm** [comment]
Or you will end up like me

Thanks for your consultation!
There was a balance display issue in Antpool, so that there would be extra
SCs/BTCs/BCHs in your balance before. Yesterday, our engineers finished
upgrading and the balance is back to normal now. You can calculate that
your daily earnings and check the balance and payment is in fact normal
now.

If you find that there are still missing earnings, please tell us your
sub-account and the date and coin type, so that we will check it for you.
After our confirmation, if you did miss earnings, we will send
compensations later.

Sorry for the inconvenience and Thanks for your support and understanding.
Please let us know if you have additional questions or concerns.

Best regards,
Joy
Bitmain




________________________________

Always order products directly from our website: www.bitmain.com
"Solved" means we replied - we still work on your issue until it is
resolved.


May 3, 21:33 CST

I am missing 100,000SC(From Upgrades to the control panel) thousand sc
coins I want to transfer and your control panel is broken! Attached is the
pps payout

Attachment(s)
收益历史记录_20180503132251.xls

And Still I am waiting............
